// =============================================================================
// RHSENSOERP - ENTITY METADATA
// =============================================================================
// Arquivo: src/Shared/Application/Metadata/EntityMetadata.cs
// Descrição: Modelo de metadados completos de uma entidade para UI dinâmica
// =============================================================================

namespace RhSensoERP.Shared.Application.Metadata;

/// <summary>
/// Metadados completos de uma entidade para o frontend dinâmico.
/// </summary>
public class EntityMetadata
{
    // =========================================================================
    // IDENTIFICAÇÃO
    // =========================================================================

    /// <summary>
    /// Nome da classe da entidade.
    /// Exemplo: "Banco", "Funcionario"
    /// </summary>
    public string EntityName { get; init; } = string.Empty;

    /// <summary>
    /// Nome amigável para exibição.
    /// Exemplo: "Banco", "Funcionário"
    /// </summary>
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>
    /// Nome no plural.
    /// Exemplo: "Bancos", "Funcionários"
    /// </summary>
    public string PluralName { get; init; } = string.Empty;

    /// <summary>
    /// Nome do módulo.
    /// Exemplo: "GestaoDePessoas", "Identity"
    /// </summary>
    public string ModuleName { get; init; } = string.Empty;

    // =========================================================================
    // CHAVE PRIMÁRIA
    // =========================================================================

    /// <summary>
    /// Configuração da chave primária.
    /// </summary>
    public PrimaryKeyMetadata PrimaryKey { get; init; } = new();

    // =========================================================================
    // PERMISSÕES
    // =========================================================================

    /// <summary>
    /// Configuração de permissões.
    /// </summary>
    public PermissionsMetadata Permissions { get; init; } = new();

    // =========================================================================
    // ENDPOINTS DA API
    // =========================================================================

    /// <summary>
    /// Endpoints da API REST.
    /// </summary>
    public EndpointsMetadata Endpoints { get; init; } = new();

    // =========================================================================
    // PROPRIEDADES
    // =========================================================================

    /// <summary>
    /// Lista de propriedades/campos da entidade.
    /// </summary>
    public List<PropertyMetadata> Properties { get; init; } = [];

    // =========================================================================
    // AÇÕES
    // =========================================================================

    /// <summary>
    /// Ações padrão disponíveis (CRUD).
    /// </summary>
    public ActionsMetadata Actions { get; init; } = new();

    /// <summary>
    /// Ações customizadas da entidade.
    /// </summary>
    public List<CustomActionMetadata> CustomActions { get; init; } = [];

    // =========================================================================
    // CONFIGURAÇÕES DE UI
    // =========================================================================

    /// <summary>
    /// Configurações de interface do usuário.
    /// </summary>
    public UIConfigMetadata UIConfig { get; init; } = new();
}

// =============================================================================
// METADADOS DE CHAVE PRIMÁRIA
// =============================================================================

/// <summary>
/// Metadados da chave primária da entidade.
/// </summary>
public class PrimaryKeyMetadata
{
    /// <summary>
    /// Nome da propriedade C#.
    /// </summary>
    public string PropertyName { get; init; } = "Id";

    /// <summary>
    /// Nome da coluna no banco.
    /// </summary>
    public string ColumnName { get; init; } = "id";

    /// <summary>
    /// Tipo C# da chave.
    /// </summary>
    public string Type { get; init; } = "Guid";

    /// <summary>
    /// Indica se é gerada automaticamente.
    /// </summary>
    public bool IsAutoGenerated { get; init; } = true;
}

// =============================================================================
// METADADOS DE PERMISSÕES
// =============================================================================

/// <summary>
/// Metadados de permissões da entidade.
/// </summary>
public class PermissionsMetadata
{
    /// <summary>
    /// Código do sistema (SEG, RHU, etc).
    /// </summary>
    public string CdSistema { get; init; } = string.Empty;

    /// <summary>
    /// Código da função para verificação IAEC.
    /// </summary>
    public string CdFuncao { get; init; } = string.Empty;

    /// <summary>
    /// Requer autenticação para acessar.
    /// </summary>
    public bool RequiresAuth { get; init; } = true;
}

// =============================================================================
// METADADOS DE ENDPOINTS
// =============================================================================

/// <summary>
/// Metadados dos endpoints da API.
/// </summary>
public class EndpointsMetadata
{
    /// <summary>
    /// URL base da API.
    /// Exemplo: "/api/rhu/bancos"
    /// </summary>
    public string BaseUrl { get; init; } = string.Empty;

    /// <summary>
    /// Endpoint de listagem (GET).
    /// </summary>
    public string List { get; init; } = string.Empty;

    /// <summary>
    /// Endpoint de busca por ID (GET).
    /// </summary>
    public string GetById { get; init; } = string.Empty;

    /// <summary>
    /// Endpoint de criação (POST).
    /// </summary>
    public string Create { get; init; } = string.Empty;

    /// <summary>
    /// Endpoint de atualização (PUT).
    /// </summary>
    public string Update { get; init; } = string.Empty;

    /// <summary>
    /// Endpoint de exclusão (DELETE).
    /// </summary>
    public string Delete { get; init; } = string.Empty;

    /// <summary>
    /// Endpoint de exclusão em lote (DELETE).
    /// </summary>
    public string BatchDelete { get; init; } = string.Empty;

    /// <summary>
    /// Endpoint de exportação (GET).
    /// </summary>
    public string Export { get; init; } = string.Empty;
}

// =============================================================================
// METADADOS DE AÇÕES PADRÃO
// =============================================================================

/// <summary>
/// Metadados das ações padrão (CRUD).
/// </summary>
public class ActionsMetadata
{
    /// <summary>
    /// Permite criar novos registros.
    /// </summary>
    public bool CanCreate { get; init; } = true;

    /// <summary>
    /// Permite editar registros.
    /// </summary>
    public bool CanEdit { get; init; } = true;

    /// <summary>
    /// Permite excluir registros.
    /// </summary>
    public bool CanDelete { get; init; } = true;

    /// <summary>
    /// Permite exclusão em lote.
    /// </summary>
    public bool CanBatchDelete { get; init; } = true;

    /// <summary>
    /// Permite exportação.
    /// </summary>
    public bool CanExport { get; init; } = true;

    /// <summary>
    /// Permite importação.
    /// </summary>
    public bool CanImport { get; init; } = false;

    /// <summary>
    /// Permite impressão.
    /// </summary>
    public bool CanPrint { get; init; } = true;

    /// <summary>
    /// Permite visualizar detalhes.
    /// </summary>
    public bool CanView { get; init; } = true;
}

// =============================================================================
// METADADOS DE AÇÕES CUSTOMIZADAS
// =============================================================================

/// <summary>
/// Metadados de uma ação customizada.
/// </summary>
public class CustomActionMetadata
{
    /// <summary>
    /// Identificador único da ação.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// Texto exibido no botão.
    /// </summary>
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>
    /// Ícone (FontAwesome).
    /// </summary>
    public string Icon { get; init; } = string.Empty;

    /// <summary>
    /// Classe CSS do botão.
    /// </summary>
    public string CssClass { get; init; } = "btn-secondary";

    /// <summary>
    /// Mensagem de confirmação.
    /// </summary>
    public string? ConfirmMessage { get; init; }

    /// <summary>
    /// Endpoint da API.
    /// </summary>
    public string Endpoint { get; init; } = string.Empty;

    /// <summary>
    /// Método HTTP.
    /// </summary>
    public string HttpMethod { get; init; } = "POST";

    /// <summary>
    /// Exibir na listagem.
    /// </summary>
    public bool ShowInList { get; init; } = true;

    /// <summary>
    /// Exibir no formulário.
    /// </summary>
    public bool ShowInForm { get; init; } = true;

    /// <summary>
    /// Permissão necessária.
    /// </summary>
    public string? RequiredPermission { get; init; }
}

// =============================================================================
// METADADOS DE CONFIGURAÇÃO DE UI
// =============================================================================

/// <summary>
/// Metadados de configuração da interface.
/// </summary>
public class UIConfigMetadata
{
    /// <summary>
    /// Ícone da entidade (FontAwesome).
    /// </summary>
    public string? Icon { get; init; }

    /// <summary>
    /// Cor tema da entidade.
    /// </summary>
    public string? Color { get; init; }

    /// <summary>
    /// Tamanho padrão da página.
    /// </summary>
    public int PageSize { get; init; } = 10;

    /// <summary>
    /// Opções de tamanho de página.
    /// </summary>
    public int[] PageSizeOptions { get; init; } = [10, 25, 50, 100];

    /// <summary>
    /// Campo padrão de ordenação.
    /// </summary>
    public string DefaultSortField { get; init; } = string.Empty;

    /// <summary>
    /// Direção padrão de ordenação.
    /// </summary>
    public string DefaultSortDirection { get; init; } = "asc";

    /// <summary>
    /// Exibir breadcrumb.
    /// </summary>
    public bool ShowBreadcrumb { get; init; } = true;

    /// <summary>
    /// Exibir título da página.
    /// </summary>
    public bool ShowTitle { get; init; } = true;
}