// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_atendimento")]
    public class MsoAtendimento
    {
        [Column("cod_empregado")]
        public int CodEmpregado { get; set; }
        [Column("data_atendimento")]
        public DateTime DataAtendimento { get; set; }
        [Column("cod_cid")]
        [StringLength(10)]
        [Required]
        public string CodCid { get; set; }
        [Column("desc_ocorrencia")]
        public string DescOcorrencia { get; set; }
        [Column("cod_registro")]
        public int CodRegistro { get; set; }
        [Column("cod_profsaude")]
        public int? CodProfsaude { get; set; }
    }
}