// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_atendimento_itens", Schema = "dbo")]
    public class MsoAtendimentoItens
    {
        [Column("cod_empregado")]
        public int CodEmpregado { get; set; }
        [Column("data_atendimento")]
        public DateTime DataAtendimento { get; set; }
        [Column("cod_tpconsulta")]
        public int CodTpconsulta { get; set; }
        [Column("cod_registro")]
        public int CodRegistro { get; set; }
    }
}