// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_consulta_exame", Schema = "dbo")]
    public class MsoConsultaExame
    {
        [Column("cod_consulta")]
        public int CodConsulta { get; set; }
        [Column("cod_empregado")]
        public int CodEmpregado { get; set; }
        [Column("cod_exame")]
        public int CodExame { get; set; }
        [Column("cod_prestador")]
        public int? CodPrestador { get; set; }
        [Column("data_exame")]
        public DateTime DataExame { get; set; }
        [Column("data_entrega")]
        public DateTime? DataEntrega { get; set; }
        [Column("cod_avaliacao")]
        public int? CodAvaliacao { get; set; }
        [Column("ch_resultado")]
        public int? ChResultado { get; set; }
        [Column("vl_resultado")]
        public decimal? VlResultado { get; set; }
        [Column("desc_resultado")]
        [StringLength(255)]
        public string DescResultado { get; set; }
    }
}