// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_consulta_geral", Schema = "dbo")]
    public class MsoConsultaGeral
    {
        [Column("cod_consulta")]
        public int CodConsulta { get; set; }
        [Column("ch_nutricional")]
        [StringLength(1)]
        public string ChNutricional { get; set; }
        [Column("ch_facies")]
        [StringLength(1)]
        public string ChFacies { get; set; }
        [Column("ch_atitude")]
        [StringLength(1)]
        public string ChAtitude { get; set; }
        [Column("ch_pele")]
        [StringLength(1)]
        public string ChPele { get; set; }
        [Column("ch_mucosa")]
        [StringLength(1)]
        public string ChMucosa { get; set; }
        [Column("ch_ganglios")]
        [StringLength(1)]
        public string ChGanglios { get; set; }
        [Column("desc_obs")]
        [StringLength(255)]
        public string DescObs { get; set; }
    }
}