// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_especialidade", Schema = "dbo")]
    public class MsoEspecialidade
    {
        [Column("cod_especialidade")]
        public int CodEspecialidade { get; set; }
        [Column("desc_especialidade")]
        public string DescEspecialidade { get; set; }
        [Column("sigla_registro")]
        [StringLength(10)]
        public string SiglaRegistro { get; set; }
        [Column("flatende_agenda")]
        [StringLength(1)]
        public string FlatendeAgenda { get; set; }
    }
}