// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Core.MSO.Entities
{
    [Table("mso_exame_grupo", Schema = "dbo")]
    public class MsoExameGrupo
    {
        [Column("cod_grupo")]
        public int CodGrupo { get; set; }
        [Column("cod_exame")]
        public int CodExame { get; set; }
        [Column("fladmissao")]
        public string Fladmissao { get; set; }
        [Column("fldemissao")]
        public string Fldemissao { get; set; }
        [Column("Idade_inicial")]
        public int? IdadeInicial { get; set; }
        [Column("validade_meses")]
        public int? ValidadeMeses { get; set; }
        [Column("flsexo")]
        [StringLength(1)]
        [Required]
        public string Flsexo { get; set; }
    }
}