// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_empregado", Schema = "dbo")]
    public class MsoEmpregado
    {
        [Column("cod_empregado")]
        public int CodEmpregado { get; set; }
        [Column("cod_tpempregado")]
        public int CodTpempregado { get; set; }
        [Column("nome_empregado")]
        [StringLength(60)]
        [Required]
        public string NomeEmpregado { get; set; }
        [Column("cod_funcao")]
        public int CodFuncao { get; set; }
        [Column("cod_empresa")]
        public int CodEmpresa { get; set; }
        [Column("cdcolab")]
        [StringLength(6)]
        public string Cdcolab { get; set; }
        [Column("data_nascimento")]
        public DateTime? DataNascimento { get; set; }
        [Column("local_nascimento")]
        [StringLength(60)]
        public string LocalNascimento { get; set; }
        [Column("cod_sexo")]
        [StringLength(1)]
        public string CodSexo { get; set; }
        [Column("cod_sangue")]
        [StringLength(2)]
        public string CodSangue { get; set; }
        [Column("cod_raca")]
        [StringLength(2)]
        public string CodRaca { get; set; }
        [Column("num_cpf")]
        [StringLength(11)]
        public string NumCpf { get; set; }
        [Column("estado_civil")]
        [StringLength(1)]
        public string EstadoCivil { get; set; }
        [Column("desc_endereco")]
        [StringLength(60)]
        public string DescEndereco { get; set; }
        [Column("desc_compl")]
        [StringLength(60)]
        public string DescCompl { get; set; }
        [Column("cod_municipio")]
        [StringLength(5)]
        public string CodMunicipio { get; set; }
        [Column("sigla_uf")]
        [StringLength(2)]
        public string SiglaUf { get; set; }
        [Column("numero_cep")]
        [StringLength(8)]
        public string NumeroCep { get; set; }
        [Column("num_telefone1")]
        [StringLength(30)]
        public string NumTelefone1 { get; set; }
        [Column("num_telefone2")]
        [StringLength(15)]
        public string NumTelefone2 { get; set; }
        [Column("desc_setor")]
        [StringLength(100)]
        public string DescSetor { get; set; }
        [Column("ch_ativo")]
        [StringLength(1)]
        public string ChAtivo { get; set; }
        [Column("desc_email")]
        [StringLength(80)]
        public string DescEmail { get; set; }
        [Column("numero_rg")]
        [StringLength(15)]
        public string NumeroRg { get; set; }
        [Column("serie_rg")]
        [StringLength(20)]
        public string SerieRg { get; set; }
        [Column("cod_matricula")]
        [StringLength(8)]
        public string CodMatricula { get; set; }
        [Column("cod_tpjornada")]
        [StringLength(1)]
        public string CodTpjornada { get; set; }
        [Column("desc_bairro")]
        [StringLength(40)]
        public string DescBairro { get; set; }
        [Column("cod_nacionalidade")]
        [StringLength(2)]
        public string CodNacionalidade { get; set; }
        [Column("cod_ccusto")]
        [StringLength(5)]
        public string CodCcusto { get; set; }
        [Column("cod_instrucao")]
        [StringLength(2)]
        public string CodInstrucao { get; set; }
        [Column("cod_convocacao")]
        public int? CodConvocacao { get; set; }
        [Column("cod_grupo")]
        public int? CodGrupo { get; set; }
        [Column("dtadmissao")]
        public DateTime? Dtadmissao { get; set; }
        [Column("nopis")]
        [StringLength(11)]
        public string Nopis { get; set; }
        [Column("codcateg")]
        public int? Codcateg { get; set; }
        [Column("cod_filial")]
        public int? CodFilial { get; set; }
        [Column("dtdemissao")]
        public DateTime? Dtdemissao { get; set; }
        [Column("cod_empregadoSesi")]
        public int? CodEmpregadosesi { get; set; }
        [Column("nmpaicolab")]
        [StringLength(60)]
        public string Nmpaicolab { get; set; }
        [Column("nmmaecolab")]
        [StringLength(60)]
        public string Nmmaecolab { get; set; }
        [Column("end_numero")]
        [StringLength(10)]
        public string EndNumero { get; set; }
        [Column("cod_cdcarreira")]
        public int? CodCdcarreira { get; set; }
        [Column("desc_localtrab")]
        [StringLength(60)]
        public string DescLocaltrab { get; set; }
        [Column("idcodltrab")]
        public decimal? Idcodltrab { get; set; }
    }
}