// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_empresa", Schema = "dbo")]
    public class MsoEmpresa
    {
        [Column("cod_empresa")]
        public int CodEmpresa { get; set; }
        [Column("rzsocial_empresa")]
        [StringLength(60)]
        [Required]
        public string RzsocialEmpresa { get; set; }
        [Column("nfantasia_empresa")]
        [StringLength(30)]
        [Required]
        public string NfantasiaEmpresa { get; set; }
        [Column("cnpj_cpf")]
        [StringLength(14)]
        public string CnpjCpf { get; set; }
        [Column("desc_endereco")]
        [StringLength(60)]
        public string DescEndereco { get; set; }
        [Column("desc_complemento")]
        [StringLength(60)]
        public string DescComplemento { get; set; }
        [Column("cod_municipio")]
        [StringLength(5)]
        public string CodMunicipio { get; set; }
        [Column("sigla_uf")]
        [StringLength(2)]
        public string SiglaUf { get; set; }
        [Column("numero_cep")]
        [StringLength(8)]
        public string NumeroCep { get; set; }
        [Column("nome_responsavel")]
        [StringLength(60)]
        public string NomeResponsavel { get; set; }
        [Column("endereco_eletronico")]
        [StringLength(80)]
        public string EnderecoEletronico { get; set; }
        [Column("ch_terceiro")]
        [StringLength(1)]
        [Required]
        public string ChTerceiro { get; set; }
        [Column("ch_ativo")]
        [StringLength(1)]
        [Required]
        public string ChAtivo { get; set; }
        [Column("cod_empreiteira")]
        public int? CodEmpreiteira { get; set; }
        [Column("dirlogotipo")]
        [StringLength(255)]
        public string Dirlogotipo { get; set; }
    }
}