// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Core.MSO.Entities
{
    [Table("mso_funcao", Schema = "dbo")]
    public class MsoFuncao
    {
        [Column("cod_funcao")]
        public int CodFuncao { get; set; }
        [Column("desc_funcao")]
        public string DescFuncao { get; set; }
        [Column("desc_atividade")]
        public string DescAtividade { get; set; }
        [Column("cdcargo")]
        [StringLength(5)]
        public string Cdcargo { get; set; }
        [Column("cod_cbo")]
        [StringLength(6)]
        public string CodCbo { get; set; }
        [Column("ch_ativo")]
        public int? ChAtivo { get; set; }
    }
}