// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_profsaude", Schema = "dbo")]
    public class MsoProfsaude
    {
        [Column("cod_profsaude")]
        public int CodProfsaude { get; set; }
        [Column("cod_especialidade")]
        public int? CodEspecialidade { get; set; }
        [Column("nome_profsaude")]
        public string NomeProfsaude { get; set; }
        [Column("end_profsaude")]
        public string EndProfsaude { get; set; }
        [Column("comp_end_profsaude")]
        public string CompEndProfsaude { get; set; }
        [Column("bai_profsaude")]
        [StringLength(20)]
        public string BaiProfsaude { get; set; }
        [Column("muni_profsaude")]
        [StringLength(5)]
        public string MuniProfsaude { get; set; }
        [Column("cep_profsaude")]
        [StringLength(18)]
        public string CepProfsaude { get; set; }
        [Column("notel1_profsaude")]
        public string Notel1Profsaude { get; set; }
        [Column("notel2_profsaude")]
        public string Notel2Profsaude { get; set; }
        [Column("nocelular_profsaude")]
        public string NocelularProfsaude { get; set; }
        [Column("uf_profsaude")]
        public string UfProfsaude { get; set; }
        [Column("num_registro")]
        [StringLength(10)]
        public string NumRegistro { get; set; }
        [Column("cdusuario")]
        [StringLength(30)]
        public string Cdusuario { get; set; }
        [Column("ch_ativo")]
        [StringLength(1)]
        public string ChAtivo { get; set; }
        [Column("flrespcmso")]
        [StringLength(1)]
        public string Flrespcmso { get; set; }
        [Column("numero_rqe")]
        [StringLength(20)]
        public string NumeroRqe { get; set; }
        [Column("cpf_profsaude")]
        [StringLength(11)]
        public string CpfProfsaude { get; set; }
        [Column("nis_profsaude")]
        [StringLength(11)]
        public string NisProfsaude { get; set; }
        [Column("id")]
        public Guid Id { get; set; }
        [Column("flativo")]
        [StringLength(1)]
        public string Flativo { get; set; }
        [Column("flprioridadeatend")]
        public int? Flprioridadeatend { get; set; }
    }
}