// <auto-generated />
// ReSharper disable All
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RhSensoERP.Domain.MSO.Entities
{
    [Table("mso_tpatende", Schema = "dbo")]
    public class MsoTpatende
    {
        [Column("cod_tpatende")]
        public int CodTpatende { get; set; }
        [Column("desc_tpatende")]
        [StringLength(60)]
        public string DescTpatende { get; set; }
    }
}