// =============================================================================
// GERADOR FULL-STACK v3.8 - WEB MODELS TEMPLATE (CORRIGIDO - AUDITORIA COMPLETA)
// Baseado em RhSensoERP.CrudTool v2.0
// v3.8 - CORRIGIDO: Exclui TODOS os campos de auditoria e sistema
// v3.6 - CORRECAO: Excluir campos de auditoria em Create/Update Requests
// v3.2 - Organiza Models por modulo/entidade
// =============================================================================

using GeradorEntidades.Models;
using System.Text;

namespace GeradorEntidades.Templates;

/// <summary>
/// Gera Models para o projeto Web.
/// v3.8: Exclui TODOS os campos de auditoria e sistema dos Requests.
/// 
/// CAMPOS EXCLUIDOS DOS REQUESTS:
/// - Auditoria: CreatedAtUtc, UpdatedAtUtc, CreatedByUserId, UpdatedByUserId
/// - Sistema: TenantId, IdSaaS, RowVersion, IsDeleted
/// - PKs auto-geradas: Id (Identity), Guid
/// 
/// CAMPOS MANTIDOS NO DTO (para exibicao):
/// - Todos os campos, incluindo auditoria
/// </summary>
public static class WebModelsTemplate
{
    /// <summary>
    /// Gera o DTO de leitura.
    /// INCLUI CAMPOS DE AUDITORIA (para exibir na tela apos salvar).
    /// </summary>
    public static GeneratedFile GenerateDto(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);
        var properties = GenerateProperties(entity.Properties);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.8
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// DTO de leitura para {entity.DisplayName}.
/// Compativel com backend: {entity.BackendNamespace ?? $"RhSensoERP.Modules.{entity.Module}.Application.DTOs"}.{entity.Name}Dto
/// </summary>
public class {entity.Name}Dto
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"{entity.Name}Dto.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/{entity.Name}Dto.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o Request de criacao.
    /// EXCLUI PKs auto-geradas E campos de auditoria/sistema.
    /// PKs de texto (nao auto-geradas) sao incluidas.
    /// </summary>
    public static GeneratedFile GenerateCreateRequest(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        // v3.8: Exclui PKs auto-geradas E campos de auditoria/sistema
        var createProps = entity.Properties
            .Where(p => !p.IsReadOnly &&
                        !IsAutoGeneratedPrimaryKey(p) &&
                        !IsAuditOrSystemField(p))
            .ToList();

        var properties = GeneratePropertiesWithValidation(createProps, isCreate: true);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.8
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// Request para criacao de {entity.DisplayName}.
/// Compativel com backend: Create{entity.Name}Request
/// </summary>
public class Create{entity.Name}Request
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"Create{entity.Name}Request.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/Create{entity.Name}Request.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o Request de atualizacao.
    /// EXCLUI PKs E campos de auditoria/sistema.
    /// PKs nunca sao editaveis no Update (nem mesmo as de texto).
    /// </summary>
    public static GeneratedFile GenerateUpdateRequest(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        // v3.8: No Update, NENHUMA PK e editavel E exclui campos de auditoria/sistema
        var updateProps = entity.Properties
            .Where(p => !p.IsPrimaryKey &&
                        !p.IsReadOnly &&
                        !IsAuditOrSystemField(p))
            .ToList();

        var properties = GeneratePropertiesWithValidation(updateProps, isCreate: false);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.8
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// Request para atualizacao de {entity.DisplayName}.
/// Compativel com backend: Update{entity.Name}Request
/// </summary>
public class Update{entity.Name}Request
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"Update{entity.Name}Request.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/Update{entity.Name}Request.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o ListViewModel que herda de BaseListViewModel.
    /// </summary>
    public static GeneratedFile GenerateListViewModel(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.8
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using RhSensoERP.Web.Models.Base;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// ViewModel para listagem de {entity.DisplayName}.
/// Herda de BaseListViewModel que ja contem permissoes e configuracoes de DataTables.
/// </summary>
public class {entity.Name}ListViewModel : BaseListViewModel
{{
    public {entity.Name}ListViewModel()
    {{
        // Inicializa propriedades padrao
        InitializeDefaults(""{entity.Name}"", ""{entity.DisplayName}"");
        
        // Configuracoes especificas
        PageTitle = ""{entity.DisplayName}"";
        PageIcon = ""{entity.Icon}"";
        CdFuncao = ""{entity.CdFuncao}"";
    }}

    /// <summary>
    /// Itens da listagem (para uso sem DataTables server-side).
    /// </summary>
    public List<{entity.Name}Dto> Items {{ get; set; }} = new();
}}
";

        return new GeneratedFile
        {
            FileName = $"{entity.Name}ListViewModel.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/{entity.Name}ListViewModel.cs",
            Content = content,
            FileType = "Model"
        };
    }

    #region Helper Methods

    /// <summary>
    /// v3.8: Verifica se a propriedade e um campo de auditoria ou sistema.
    /// Estes campos NAO devem aparecer em Create/Update Requests.
    /// Sao preenchidos automaticamente pelo backend.
    /// </summary>
    private static bool IsAuditOrSystemField(PropertyConfig prop)
    {
        var systemFields = new[]
        {
            // =====================================================================
            // Campos de Auditoria - Padrao Legacy (SQL Server)
            // =====================================================================
            "DataCriacao", "DtCriacao",
            "UsuarioCriacao", "CriadoPor",
            "DataAtualizacao", "DtAtualizacao",
            "UsuarioAtualizacao", "AtualizadoPor",
            
            // =====================================================================
            // Campos de Auditoria - Padrao Moderno (Entity Framework)
            // =====================================================================
            "CreatedAt", "CreatedDate", "CreatedAtUtc",
            "CreatedBy", "CreatedByUser", "CreatedByUserId",
            "UpdatedAt", "ModifiedAt", "ModifiedDate", "UpdatedAtUtc",
            "UpdatedBy", "ModifiedBy", "ModifiedByUser", "UpdatedByUserId",
            
            // =====================================================================
            // Campos de Sistema (Preenchidos pelo Backend)
            // =====================================================================
            "TenantId", "IdSaaS", "IdSaas",
            "RowVersion", "Version", "Timestamp",
            "IsDeleted", "DeletedAt", "DeletedBy", "DeletedByUserId"
        };

        return systemFields.Any(f => prop.Name.Equals(f, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Verifica se a propriedade e uma PK auto-gerada.
    /// PKs de texto (string) NAO sao auto-geradas e devem aparecer no Create.
    /// </summary>
    private static bool IsAutoGeneratedPrimaryKey(PropertyConfig prop)
    {
        if (!prop.IsPrimaryKey)
            return false;

        // PKs string NAO sao auto-geradas (codigo manual como CdTptabela)
        if (prop.IsString)
            return false;

        // Identity -> auto-gerada
        if (prop.IsIdentity)
            return true;

        // Guid -> auto-gerada
        if (prop.IsGuid)
            return true;

        // Numerico (int/long) sem Identity explicito -> assumir auto-gerada
        if (prop.IsInt || prop.IsLong)
            return true;

        // Outros tipos -> assumir auto-gerada por seguranca
        return true;
    }

    /// <summary>
    /// Gera propriedades sem validacao (para DTOs de leitura).
    /// </summary>
    private static string GenerateProperties(List<PropertyConfig> properties)
    {
        var sb = new StringBuilder();

        foreach (var prop in properties)
        {
            // Comentario XML com DisplayName
            if (!string.IsNullOrEmpty(prop.DisplayName))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {prop.DisplayName}");
                sb.AppendLine($"    /// </summary>");
            }

            // Propriedade
            sb.AppendLine($"    {prop.GetPropertyDeclaration()}");
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Gera propriedades com validacao (para Requests de Create/Update).
    /// PKs de texto sao obrigatorias no Create.
    /// </summary>
    private static string GeneratePropertiesWithValidation(List<PropertyConfig> properties, bool isCreate = false)
    {
        var sb = new StringBuilder();

        foreach (var prop in properties)
        {
            // Comentario XML
            if (!string.IsNullOrEmpty(prop.DisplayName))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {prop.DisplayName}");
                if (prop.IsPrimaryKey && isCreate)
                {
                    sb.AppendLine($"    /// (Chave Primaria - obrigatorio na criacao)");
                }
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    [Display(Name = \"{prop.DisplayName}\")]");
            }

            // Required - PKs de texto sao sempre obrigatorias no Create
            bool isRequired = prop.Required && !prop.IsNullable;
            if (prop.IsPrimaryKey && isCreate)
            {
                isRequired = true;
            }

            if (isRequired)
            {
                var errorMsg = !string.IsNullOrEmpty(prop.DisplayName)
                    ? prop.DisplayName
                    : prop.Name;
                sb.AppendLine($"    [Required(ErrorMessage = \"{errorMsg} e obrigatorio\")]");
            }

            // StringLength
            if (prop.MaxLength.HasValue && prop.IsString)
            {
                if (prop.MinLength.HasValue && prop.MinLength.Value > 0)
                {
                    sb.AppendLine($"    [StringLength({prop.MaxLength.Value}, MinimumLength = {prop.MinLength.Value}, " +
                                 $"ErrorMessage = \"{prop.DisplayName ?? prop.Name} deve ter entre {{2}} e {{1}} caracteres\")]");
                }
                else
                {
                    sb.AppendLine($"    [StringLength({prop.MaxLength.Value}, " +
                                 $"ErrorMessage = \"{prop.DisplayName ?? prop.Name} deve ter no maximo {{1}} caracteres\")]");
                }
            }

            // Propriedade
            sb.AppendLine($"    {prop.GetPropertyDeclaration()}");
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Converte nome do modulo para path de pasta.
    /// </summary>
    private static string GetModulePath(string moduleName)
    {
        if (string.IsNullOrEmpty(moduleName))
            return "Common";

        return moduleName;
    }

    #endregion
}