// =============================================================================
// GERADOR FULL-STACK v3.6 - WEB MODELS TEMPLATE (CORRIGIDO)
// Baseado em RhSensoERP.CrudTool v2.0
// v3.6 - CORREÇÃO: Excluir campos de auditoria em Create/Update Requests
// v3.2 - Organiza Models por módulo/entidade
// =============================================================================

using GeradorEntidades.Models;
using System.Text;

namespace GeradorEntidades.Templates;

/// <summary>
/// Gera Models para o projeto Web.
/// v3.6: Exclui campos de auditoria dos Requests (mas mantém no DTO).
/// </summary>
public static class WebModelsTemplate
{
    /// <summary>
    /// Gera o DTO de leitura.
    /// ✅ INCLUI CAMPOS DE AUDITORIA (para exibir na tela após salvar).
    /// </summary>
    public static GeneratedFile GenerateDto(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);
        var properties = GenerateProperties(entity.Properties);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.6
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// DTO de leitura para {entity.DisplayName}.
/// Compatível com backend: {entity.BackendNamespace ?? $"RhSensoERP.Modules.{entity.Module}.Application.DTOs"}.{entity.Name}Dto
/// </summary>
public class {entity.Name}Dto
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"{entity.Name}Dto.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/{entity.Name}Dto.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o Request de criação.
    /// ❌ EXCLUI PKs auto-geradas E campos de auditoria.
    /// PKs de texto (não auto-geradas) são incluídas.
    /// </summary>
    public static GeneratedFile GenerateCreateRequest(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        // ✅ v3.6: Exclui PKs auto-geradas E campos de auditoria
        var createProps = entity.Properties
            .Where(p => !p.IsReadOnly &&
                        !IsAutoGeneratedPrimaryKey(p) &&
                        !IsAuditField(p))
            .ToList();

        var properties = GeneratePropertiesWithValidation(createProps, isCreate: true);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.6
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// Request para criação de {entity.DisplayName}.
/// Compatível com backend: Create{entity.Name}Request
/// </summary>
public class Create{entity.Name}Request
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"Create{entity.Name}Request.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/Create{entity.Name}Request.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o Request de atualização.
    /// ❌ EXCLUI PKs E campos de auditoria.
    /// PKs nunca são editáveis no Update (nem mesmo as de texto).
    /// </summary>
    public static GeneratedFile GenerateUpdateRequest(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        // ✅ v3.6: No Update, NENHUMA PK é editável E exclui campos de auditoria
        var updateProps = entity.Properties
            .Where(p => !p.IsPrimaryKey &&
                        !p.IsReadOnly &&
                        !IsAuditField(p))
            .ToList();

        var properties = GeneratePropertiesWithValidation(updateProps, isCreate: false);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.6
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// Request para atualização de {entity.DisplayName}.
/// Compatível com backend: Update{entity.Name}Request
/// </summary>
public class Update{entity.Name}Request
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"Update{entity.Name}Request.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/Update{entity.Name}Request.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o ListViewModel que herda de BaseListViewModel.
    /// </summary>
    public static GeneratedFile GenerateListViewModel(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v3.6
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using RhSensoERP.Web.Models.Base;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// ViewModel para listagem de {entity.DisplayName}.
/// Herda de BaseListViewModel que já contém permissões e configurações de DataTables.
/// </summary>
public class {entity.Name}ListViewModel : BaseListViewModel
{{
    public {entity.Name}ListViewModel()
    {{
        // Inicializa propriedades padrão
        InitializeDefaults(""{entity.Name}"", ""{entity.DisplayName}"");
        
        // Configurações específicas
        PageTitle = ""{entity.DisplayName}"";
        PageIcon = ""{entity.Icon}"";
        CdFuncao = ""{entity.CdFuncao}"";
    }}

    /// <summary>
    /// Itens da listagem (para uso sem DataTables server-side).
    /// </summary>
    public List<{entity.Name}Dto> Items {{ get; set; }} = new();
}}
";

        return new GeneratedFile
        {
            FileName = $"{entity.Name}ListViewModel.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/{entity.Name}ListViewModel.cs",
            Content = content,
            FileType = "Model"
        };
    }

    #region Helper Methods

    /// <summary>
    /// ✅ v3.6: Verifica se a propriedade é um campo de auditoria.
    /// Campos de auditoria NÃO devem aparecer em Create/Update Requests.
    /// </summary>
    private static bool IsAuditField(PropertyConfig prop)
    {
        var auditFields = new[]
        {
            "DataCriacao", "DtCriacao", "CreatedAt", "CreatedDate",
            "UsuarioCriacao", "CreatedBy", "CreatedByUser", "CriadoPor",
            "DataAtualizacao", "DtAtualizacao", "UpdatedAt", "ModifiedAt", "ModifiedDate",
            "UsuarioAtualizacao", "UpdatedBy", "ModifiedBy", "ModifiedByUser", "AtualizadoPor"
        };

        return auditFields.Any(f => prop.Name.Equals(f, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Verifica se a propriedade é uma PK auto-gerada.
    /// PKs de texto (string) NÃO são auto-geradas e devem aparecer no Create.
    /// </summary>
    private static bool IsAutoGeneratedPrimaryKey(PropertyConfig prop)
    {
        if (!prop.IsPrimaryKey)
            return false;

        // PKs string NÃO são auto-geradas (código manual como CdTptabela)
        if (prop.IsString)
            return false;

        // Identity → auto-gerada
        if (prop.IsIdentity)
            return true;

        // Guid → auto-gerada
        if (prop.IsGuid)
            return true;

        // Numérico (int/long) sem Identity explícito → assumir auto-gerada
        if (prop.IsInt || prop.IsLong)
            return true;

        // Outros tipos → assumir auto-gerada por segurança
        return true;
    }

    /// <summary>
    /// Gera propriedades sem validação (para DTOs de leitura).
    /// </summary>
    private static string GenerateProperties(List<PropertyConfig> properties)
    {
        var sb = new StringBuilder();

        foreach (var prop in properties)
        {
            // Comentário XML com DisplayName
            if (!string.IsNullOrEmpty(prop.DisplayName))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {prop.DisplayName}");
                sb.AppendLine($"    /// </summary>");
            }

            // Propriedade
            sb.AppendLine($"    {prop.GetPropertyDeclaration()}");
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Gera propriedades com validação (para Requests de Create/Update).
    /// PKs de texto são obrigatórias no Create.
    /// </summary>
    private static string GeneratePropertiesWithValidation(List<PropertyConfig> properties, bool isCreate = false)
    {
        var sb = new StringBuilder();

        foreach (var prop in properties)
        {
            // Comentário XML
            if (!string.IsNullOrEmpty(prop.DisplayName))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {prop.DisplayName}");
                if (prop.IsPrimaryKey && isCreate)
                {
                    sb.AppendLine($"    /// (Chave Primária - obrigatório na criação)");
                }
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    [Display(Name = \"{prop.DisplayName}\")]");
            }

            // Required - PKs de texto são sempre obrigatórias no Create
            bool isRequired = prop.Required && !prop.IsNullable;
            if (prop.IsPrimaryKey && isCreate)
            {
                isRequired = true;
            }

            if (isRequired)
            {
                var errorMsg = !string.IsNullOrEmpty(prop.DisplayName)
                    ? prop.DisplayName
                    : prop.Name;
                sb.AppendLine($"    [Required(ErrorMessage = \"{errorMsg} é obrigatório\")]");
            }

            // StringLength
            if (prop.MaxLength.HasValue && prop.IsString)
            {
                if (prop.MinLength.HasValue && prop.MinLength.Value > 0)
                {
                    sb.AppendLine($"    [StringLength({prop.MaxLength.Value}, MinimumLength = {prop.MinLength.Value}, " +
                                 $"ErrorMessage = \"{prop.DisplayName ?? prop.Name} deve ter entre {{2}} e {{1}} caracteres\")]");
                }
                else
                {
                    sb.AppendLine($"    [StringLength({prop.MaxLength.Value}, " +
                                 $"ErrorMessage = \"{prop.DisplayName ?? prop.Name} deve ter no máximo {{1}} caracteres\")]");
                }
            }

            // Propriedade
            sb.AppendLine($"    {prop.GetPropertyDeclaration()}");
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Converte nome do módulo para path de pasta.
    /// </summary>
    private static string GetModulePath(string moduleName)
    {
        if (string.IsNullOrEmpty(moduleName))
            return "Common";

        return moduleName;
    }

    #endregion
}