// =============================================================================
// GERADOR FULL-STACK v4.0 - WEB MODELS TEMPLATE
// ⭐ v4.0 - SELECT2 LOOKUP AUTOMÁTICO - Gera DTOs de Lookup
// v3.8 - CORRIGIDO: Exclui TODOS os campos de auditoria e sistema
// v3.6 - CORREÇÃO: Excluir campos de auditoria em Create/Update Requests
// v3.2 - Organiza Models por modulo/entidade
// =============================================================================
// ✅ ARQUIVO VERIFICADO E APROVADO - SELECT2 v4.0 COMPLETO
// =============================================================================

using GeradorEntidades.Models;
using System.Text;

namespace GeradorEntidades.Templates;

/// <summary>
/// Gera Models para o projeto Web.
/// v4.0: Gera DTOs de Lookup automáticos para campos Select2.
/// v3.8: Exclui TODOS os campos de auditoria e sistema dos Requests.
/// 
/// CAMPOS EXCLUIDOS DOS REQUESTS:
/// - Auditoria: CreatedAtUtc, UpdatedAtUtc, CreatedByUserId, UpdatedByUserId
/// - Sistema: TenantId, IdSaaS, RowVersion, IsDeleted
/// - PKs auto-geradas: Id (Identity), Guid
/// 
/// CAMPOS MANTIDOS NO DTO (para exibição):
/// - Todos os campos, incluindo auditoria
/// </summary>
public static class WebModelsTemplate
{
    /// <summary>
    /// Gera o DTO de leitura.
    /// INCLUI CAMPOS DE AUDITORIA (para exibir na tela após salvar).
    /// </summary>
    public static GeneratedFile GenerateDto(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);
        var properties = GenerateProperties(entity.Properties);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v4.0
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// DTO de leitura para {entity.DisplayName}.
/// Compatível com backend: {entity.BackendNamespace ?? $"RhSensoERP.Modules.{entity.Module}.Application.DTOs"}.{entity.Name}Dto
/// </summary>
public class {entity.Name}Dto
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"{entity.Name}Dto.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/{entity.Name}Dto.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o Request de criação.
    /// EXCLUI PKs auto-geradas E campos de auditoria/sistema.
    /// PKs de texto (não auto-geradas) são incluídas.
    /// </summary>
    public static GeneratedFile GenerateCreateRequest(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        // v3.8: Exclui PKs auto-geradas E campos de auditoria/sistema
        var createProps = entity.Properties
            .Where(p => !p.IsReadOnly &&
                        !IsAutoGeneratedPrimaryKey(p) &&
                        !IsAuditOrSystemField(p))
            .ToList();

        var properties = GeneratePropertiesWithValidation(createProps, isCreate: true);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v4.0
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// Request para criação de {entity.DisplayName}.
/// Compatível com backend: Create{entity.Name}Request
/// </summary>
public class Create{entity.Name}Request
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"Create{entity.Name}Request.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/Create{entity.Name}Request.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o Request de atualização.
    /// EXCLUI PKs E campos de auditoria/sistema.
    /// PKs nunca são editáveis no Update (nem mesmo as de texto).
    /// </summary>
    public static GeneratedFile GenerateUpdateRequest(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        // v3.8: No Update, NENHUMA PK é editável E exclui campos de auditoria/sistema
        var updateProps = entity.Properties
            .Where(p => !p.IsPrimaryKey &&
                        !p.IsReadOnly &&
                        !IsAuditOrSystemField(p))
            .ToList();

        var properties = GeneratePropertiesWithValidation(updateProps, isCreate: false);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v4.0
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// Request para atualização de {entity.DisplayName}.
/// Compatível com backend: Update{entity.Name}Request
/// </summary>
public class Update{entity.Name}Request
{{
{properties}
}}
";

        return new GeneratedFile
        {
            FileName = $"Update{entity.Name}Request.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/Update{entity.Name}Request.cs",
            Content = content,
            FileType = "Model"
        };
    }

    /// <summary>
    /// Gera o ListViewModel que herda de BaseListViewModel.
    /// </summary>
    public static GeneratedFile GenerateListViewModel(EntityConfig entity)
    {
        var modulePath = GetModulePath(entity.Module);

        var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v4.0
// Entity: {entity.Name}
// Module: {entity.Module}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================
using RhSensoERP.Web.Models.Base;

namespace RhSensoERP.Web.Models.{modulePath}.{entity.Name};

/// <summary>
/// ViewModel para listagem de {entity.DisplayName}.
/// Herda de BaseListViewModel que já contém permissões e configurações de DataTables.
/// </summary>
public class {entity.Name}ListViewModel : BaseListViewModel
{{
    public {entity.Name}ListViewModel()
    {{
        // Inicializa propriedades padrão
        InitializeDefaults(""{entity.Name}"", ""{entity.DisplayName}"");
        
        // Configurações específicas
        PageTitle = ""{entity.DisplayName}"";
        PageIcon = ""{entity.Icon}"";
        CdFuncao = ""{entity.CdFuncao}"";
    }}

    /// <summary>
    /// Itens da listagem (para uso sem DataTables server-side).
    /// </summary>
    public List<{entity.Name}Dto> Items {{ get; set; }} = new();
}}
";

        return new GeneratedFile
        {
            FileName = $"{entity.Name}ListViewModel.cs",
            RelativePath = $"Web/Models/{modulePath}/{entity.Name}/{entity.Name}ListViewModel.cs",
            Content = content,
            FileType = "Model"
        };
    }

    // =========================================================================
    // ⭐ v4.0: SELECT2 LOOKUP - GERAÇÃO AUTOMÁTICA DE DTOS
    // =========================================================================

    /// <summary>
    /// ⭐ v4.0: Gera DTOs simplificados para lookups de Select2.
    /// Um DTO é criado para cada campo configurado como Select2 AJAX.
    /// 
    /// EXEMPLO DE DTO GERADO:
    /// <code>
    /// public class FornecedorLookupDto
    /// {
    ///     public int Id { get; set; }
    ///     public string RazaoSocial { get; set; } = string.Empty;
    /// }
    /// </code>
    /// </summary>
    public static List<GeneratedFile> GenerateSelect2LookupDtos(EntityConfig entity)
    {
        var files = new List<GeneratedFile>();

        if (!entity.Select2Lookups.Any())
            return files;

        foreach (var lookup in entity.Select2Lookups)
        {
            var valuePascal = ToPascalCase(lookup.ValueField);
            var textPascal = ToPascalCase(lookup.TextField);

            // Determina tipo do campo VALUE baseado na propriedade FK
            var valueType = "int"; // padrão
            var relatedProp = entity.Properties.FirstOrDefault(p =>
                p.Name.Equals(lookup.PropertyName, StringComparison.OrdinalIgnoreCase));

            if (relatedProp != null)
            {
                // Usa o tipo simples (sem nullable) da FK
                valueType = relatedProp.CSharpTypeSimple;
            }

            var content = $@"// =============================================================================
// ARQUIVO GERADO POR GeradorFullStack v4.0
// DTO DE LOOKUP PARA SELECT2
// Campo: {lookup.PropertyName}
// Entidade: {lookup.EntityName}
// Data: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// =============================================================================

namespace RhSensoERP.Web.Models.Common;

/// <summary>
/// DTO simplificado para lookup de {lookup.DisplayName} em Select2.
/// Gerado automaticamente para o campo {lookup.PropertyName}.
/// </summary>
public class {lookup.DtoName}
{{
    /// <summary>
    /// Valor que será usado como ID no Select2 (campo {lookup.ValueField})
    /// </summary>
    public {valueType} {valuePascal} {{ get; set; }}
    
    /// <summary>
    /// Texto que será exibido no Select2 (campo {lookup.TextField})
    /// </summary>
    public string {textPascal} {{ get; set; }} = string.Empty;
}}
";

            files.Add(new GeneratedFile
            {
                FileName = $"{lookup.DtoName}.cs",
                RelativePath = $"Web/Models/Common/{lookup.DtoName}.cs",
                Content = content,
                FileType = "Model"
            });
        }

        return files;
    }

    #region Helper Methods

    /// <summary>
    /// v3.8: Verifica se a propriedade é um campo de auditoria ou sistema.
    /// Estes campos NÃO devem aparecer em Create/Update Requests.
    /// São preenchidos automaticamente pelo backend.
    /// </summary>
    private static bool IsAuditOrSystemField(PropertyConfig prop)
    {
        var systemFields = new[]
        {
            // =====================================================================
            // Campos de Auditoria - Padrão Legacy (SQL Server)
            // =====================================================================
            "DataCriacao", "DtCriacao",
            "UsuarioCriacao", "CriadoPor",
            "DataAtualizacao", "DtAtualizacao",
            "UsuarioAtualizacao", "AtualizadoPor",
            
            // =====================================================================
            // Campos de Auditoria - Padrão Moderno (Entity Framework)
            // =====================================================================
            "CreatedAt", "CreatedDate", "CreatedAtUtc",
            "CreatedBy", "CreatedByUser", "CreatedByUserId",
            "UpdatedAt", "ModifiedAt", "ModifiedDate", "UpdatedAtUtc",
            "UpdatedBy", "ModifiedBy", "ModifiedByUser", "UpdatedByUserId",
            
            // =====================================================================
            // Campos de Sistema (Preenchidos pelo Backend)
            // =====================================================================
            "TenantId", "IdSaaS", "IdSaas",
            "RowVersion", "Version", "Timestamp",
            "IsDeleted", "DeletedAt", "DeletedBy", "DeletedByUserId"
        };

        return systemFields.Any(f => prop.Name.Equals(f, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Verifica se a propriedade é uma PK auto-gerada.
    /// PKs de texto (string) NÃO são auto-geradas e devem aparecer no Create.
    /// </summary>
    private static bool IsAutoGeneratedPrimaryKey(PropertyConfig prop)
    {
        if (!prop.IsPrimaryKey)
            return false;

        // PKs string NÃO são auto-geradas (código manual como CdTptabela)
        if (prop.IsString)
            return false;

        // Identity -> auto-gerada
        if (prop.IsIdentity)
            return true;

        // Guid -> auto-gerada
        if (prop.IsGuid)
            return true;

        // Numérico (int/long) sem Identity explícito -> assumir auto-gerada
        if (prop.IsInt || prop.IsLong)
            return true;

        // Outros tipos -> assumir auto-gerada por segurança
        return true;
    }

    /// <summary>
    /// Gera propriedades sem validação (para DTOs de leitura).
    /// </summary>
    private static string GenerateProperties(List<PropertyConfig> properties)
    {
        var sb = new StringBuilder();

        foreach (var prop in properties)
        {
            // Comentário XML com DisplayName
            if (!string.IsNullOrEmpty(prop.DisplayName))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {prop.DisplayName}");
                sb.AppendLine($"    /// </summary>");
            }

            // Propriedade
            sb.AppendLine($"    {prop.GetPropertyDeclaration()}");
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Gera propriedades com validação (para Requests de Create/Update).
    /// PKs de texto são obrigatórias no Create.
    /// </summary>
    private static string GeneratePropertiesWithValidation(List<PropertyConfig> properties, bool isCreate = false)
    {
        var sb = new StringBuilder();

        foreach (var prop in properties)
        {
            // Comentário XML
            if (!string.IsNullOrEmpty(prop.DisplayName))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {prop.DisplayName}");
                if (prop.IsPrimaryKey && isCreate)
                {
                    sb.AppendLine($"    /// (Chave Primária - obrigatório na criação)");
                }
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    [Display(Name = \"{prop.DisplayName}\")]");
            }

            // Required - PKs de texto são sempre obrigatórias no Create
            bool isRequired = prop.Required && !prop.IsNullable;
            if (prop.IsPrimaryKey && isCreate)
            {
                isRequired = true;
            }

            if (isRequired)
            {
                var errorMsg = !string.IsNullOrEmpty(prop.DisplayName)
                    ? prop.DisplayName
                    : prop.Name;
                sb.AppendLine($"    [Required(ErrorMessage = \"{errorMsg} é obrigatório\")]");
            }

            // StringLength
            if (prop.MaxLength.HasValue && prop.IsString)
            {
                if (prop.MinLength.HasValue && prop.MinLength.Value > 0)
                {
                    sb.AppendLine($"    [StringLength({prop.MaxLength.Value}, MinimumLength = {prop.MinLength.Value}, " +
                                 $"ErrorMessage = \"{prop.DisplayName ?? prop.Name} deve ter entre {{2}} e {{1}} caracteres\")]");
                }
                else
                {
                    sb.AppendLine($"    [StringLength({prop.MaxLength.Value}, " +
                                 $"ErrorMessage = \"{prop.DisplayName ?? prop.Name} deve ter no máximo {{1}} caracteres\")]");
                }
            }

            // Propriedade
            sb.AppendLine($"    {prop.GetPropertyDeclaration()}");
            sb.AppendLine();
        }

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// ⭐ v4.0: Helper - Converte para PascalCase.
    /// Usado para converter valueField e textField (camelCase) para propriedades C# (PascalCase).
    /// 
    /// EXEMPLOS:
    /// - "id" → "Id"
    /// - "razaoSocial" → "RazaoSocial"
    /// - "nomeCompleto" → "NomeCompleto"
    /// </summary>
    private static string ToPascalCase(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        return char.ToUpper(text[0]) + text.Substring(1);
    }

    /// <summary>
    /// Converte nome do módulo para path de pasta.
    /// </summary>
    private static string GetModulePath(string moduleName)
    {
        if (string.IsNullOrEmpty(moduleName))
            return "Common";

        return moduleName;
    }

    #endregion
}