// =============================================================================
// RHSENSOERP GENERATOR v4.9 - DTO TEMPLATE
// =============================================================================
// v4.9: FIX CRÍTICO - Exclui Id (Guid/Identity) do UpdateRequest quando NÃO é PK
//       Sem isso, backend recebe Id=Guid.Empty e AutoMapper sobrescreve entity.Id
// v4.8: CORRIGIDO - PK texto/numérica não-identity incluída no CreateRequest
// v4.6: ADICIONADO - Propriedades de navegação (ex: FornecedorRazaoSocial)
// =============================================================================
using RhSensoERP.Generators.Models;
using System.Collections.Generic;
using System.Linq;

namespace RhSensoERP.Generators.Templates;

public static class DtoTemplate
{
    public static string GenerateDto(EntityInfo info)
    {
        var props = new List<string>();

        // ✅ Propriedades escalares normais
        foreach (var p in info.DtoProperties)
        {
            props.Add($"    public {p.Type} {p.Name} {{ get; set; }}{GetDefaultValue(p)}");
        }

        // ✅ v4.6 NOVO: Propriedades de navegação
        var navigationProps = GenerateNavigationProperties(info);
        if (!string.IsNullOrEmpty(navigationProps))
        {
            props.Add("");
            props.Add("    // =========================================================================");
            props.Add("    // PROPRIEDADES DE NAVEGAÇÃO (campos de entidades relacionadas)");
            props.Add("    // =========================================================================");
            props.Add(navigationProps);
        }

        return $$"""
{{info.FileHeader}}
using System;
using System.Collections.Generic;
using {{info.Namespace}};

namespace {{info.DtoNamespace}};

/// <summary>
/// DTO para leitura de {{info.DisplayName}}.
/// </summary>
public sealed class {{info.EntityName}}Dto
{
{{string.Join("\n", props)}}
}
""";
    }

    public static string GenerateCreateRequest(EntityInfo info)
    {
        var filteredProps = info.CreateProperties
            .Where(p => !IsAuditOrTenantField(p.Name, info))
            .ToList();

        // =====================================================================
        // v4.8: Inclui PK no CreateRequest quando não é auto-gerada
        // PK Identity/Guid = auto-gerada pelo banco → NÃO incluir
        // PK texto/numérica não-identity = informada pelo usuário → INCLUIR
        // PK composta = TODAS as colunas da PK devem ser incluídas
        // =====================================================================
        if (info.HasCompositeKey)
        {
            // PK composta: inclui TODAS as colunas da PK
            var pkProps = info.Properties.Where(p => p.IsPrimaryKey).Reverse().ToList();
            foreach (var pkProp in pkProps)
            {
                if (!filteredProps.Any(p => p.Name == pkProp.Name))
                {
                    filteredProps.Insert(0, pkProp);
                }
            }

            // ✅ v4.9: Remove Id (Guid/Identity) do CreateRequest quando NÃO é PK
            // Em entidades com PK composta + Id herdado de BaseEntity,
            // o Id não deve estar no CreateRequest (é auto-gerado)
            filteredProps.RemoveAll(p => IsAutoGeneratedNonPkField(p, info));
        }
        else
        {
            var pkProp = info.Properties.FirstOrDefault(p => p.IsPrimaryKey);
            if (pkProp != null && !pkProp.IsIdentity && !pkProp.IsGuid)
            {
                // Só adiciona se ainda não estiver na lista
                if (!filteredProps.Any(p => p.Name == pkProp.Name))
                {
                    filteredProps.Insert(0, pkProp); // PK primeiro
                }
            }
        }

        var props = new List<string>();
        foreach (var p in filteredProps)
        {
            props.Add($"    public {p.Type} {p.Name} {{ get; set; }}{GetDefaultValue(p)}");
        }

        return $$"""
{{info.FileHeader}}
using System;
using System.Collections.Generic;
using {{info.Namespace}};

namespace {{info.DtoNamespace}};

/// <summary>
/// Request para criação de {{info.DisplayName}}.
/// </summary>
public sealed class Create{{info.EntityName}}Request
{
{{string.Join("\n", props)}}
}
""";
    }

    public static string GenerateUpdateRequest(EntityInfo info)
    {
        var filteredProps = info.UpdateProperties
            .Where(p => !IsAuditOrTenantField(p.Name, info))
            .ToList();

        // =====================================================================
        // ⭐ v4.9 FIX CRÍTICO: Remove campos auto-gerados do UpdateRequest
        //
        // Problema: Em entidades com PK composta (ex: CdSistema + CdGrUser),
        // o campo Id (Guid) de BaseEntity NÃO é PK mas aparece em UpdateProperties.
        // Se incluído no DTO, o backend recebe Id=Guid.Empty (00000000-...),
        // AutoMapper sobrescreve entity.Id com Guid.Empty → DbUpdateException.
        //
        // A condição .ForAllMembers(srcMember != null) NÃO protege porque:
        // Guid.Empty != null → true → AutoMapper copia o valor!
        //
        // Solução: Remover Id (e outros auto-gerados) do UpdateRequest.
        // A entidade é localizada pela PK (composta ou simples) via rota.
        // =====================================================================
        filteredProps.RemoveAll(p => IsAutoGeneratedNonPkField(p, info));

        // ✅ v4.9: Para PK composta, também remove campos de PK do Update
        // (eles vêm pela rota, não pelo body)
        if (info.HasCompositeKey)
        {
            var pkNames = new HashSet<string>(info.CompositeKeyProperties, StringComparer.OrdinalIgnoreCase);
            filteredProps.RemoveAll(p => pkNames.Contains(p.Name));
        }

        var props = new List<string>();
        foreach (var p in filteredProps)
        {
            props.Add($"    public {p.Type} {p.Name} {{ get; set; }}{GetDefaultValue(p)}");
        }

        return $$"""
{{info.FileHeader}}
using System;
using System.Collections.Generic;
using {{info.Namespace}};

namespace {{info.DtoNamespace}};

/// <summary>
/// Request para atualização de {{info.DisplayName}}.
/// Contém APENAS campos editáveis (sem PK, sem Id auto-gerado, sem auditoria).
/// </summary>
public sealed class Update{{info.EntityName}}Request
{
{{string.Join("\n", props)}}
}
""";
    }

    // =========================================================================
    // ✅ v4.6 NOVO: GERAÇÃO DE PROPRIEDADES DE NAVEGAÇÃO
    // =========================================================================

    /// <summary>
    /// Gera propriedades de navegação baseadas no atributo [NavigationDisplay].
    /// Ex: public string? FornecedorRazaoSocial { get; set; }
    /// </summary>
    private static string GenerateNavigationProperties(EntityInfo info)
    {
        var navProps = info.Navigations
            .Where(n => n.HasNavigationDisplay &&
                       n.RelationshipType == NavigationRelationshipType.ManyToOne)
            .ToList();

        if (!navProps.Any())
            return "";

        var lines = new List<string>();

        foreach (var nav in navProps)
        {
            var propName = nav.DtoPropertyNameComputed;
            var displayProp = nav.DisplayProperty;

            lines.Add($"    /// <summary>");
            lines.Add($"    /// Campo '{displayProp}' da navegação {nav.Name}.");
            lines.Add($"    /// </summary>");
            lines.Add($"    public string? {propName} {{ get; set; }}");
        }

        return string.Join("\n", lines);
    }

    // =========================================================================
    // ⭐ v4.9: HELPER - Detecta campo auto-gerado que NÃO é PK
    // =========================================================================

    /// <summary>
    /// Verifica se uma propriedade é auto-gerada E não faz parte da PK.
    /// Estes campos NÃO devem estar no Create/Update Request:
    /// - Id (Guid) herdado de BaseEntity quando PK é composta
    /// - Campos Identity (auto-incremento) quando não são a PK principal
    /// </summary>
    private static bool IsAutoGeneratedNonPkField(RhSensoERP.Generators.Models.PropertyInfo prop, EntityInfo info)
    {
        // Se é PK, não é "non-PK" - não remove
        if (prop.IsPrimaryKey) return false;

        // Campo Identity (auto-incremento) que não é PK
        if (prop.IsIdentity) return true;

        // Campo Guid chamado "Id" que não é PK
        // (herdado de BaseEntity em entidades com PK composta)
        if (prop.Name.Equals("Id", StringComparison.OrdinalIgnoreCase) &&
            (prop.IsGuid || prop.Type == "Guid"))
            return true;

        return false;
    }

    private static string GetDefaultValue(RhSensoERP.Generators.Models.PropertyInfo prop)
    {
        if (!string.IsNullOrEmpty(prop.DefaultValue))
            return $" = {prop.DefaultValue};";

        if (prop.IsString && !prop.IsNullable)
            return " = string.Empty;";

        return string.Empty;
    }

    private static bool IsAuditOrTenantField(string name, EntityInfo info)
    {
        if (name == info.CreatedAtField ||
            name == info.CreatedByField ||
            name == info.UpdatedAtField ||
            name == info.UpdatedByField)
            return true;

        var tenantFields = new[] { "TenantId", "IdSaaS", "IdSaas", "IdTenant" };
        return tenantFields.Contains(name);
    }
}