// =============================================================================
// RHSENSOERP GENERATOR v4.8 - MAPPER TEMPLATE
// =============================================================================
// v4.8: CORRIGIDO - PK texto/numérica não-identity NÃO é ignorada no Create
// v4.7: ADICIONADO - Suporte a PK composta (ignora todas as colunas da PK)
// v4.6.1: CORRIGIDO - Null-check explícito em navegações
// v4.6: ADICIONADO - Mapeamento automático de navegações
// =============================================================================
using RhSensoERP.Generators.Models;
using System.Collections.Generic;
using System.Linq;

namespace RhSensoERP.Generators.Templates;

/// <summary>
/// Template para geração de AutoMapper Profile.
/// </summary>
public static class MapperTemplate
{
    /// <summary>
    /// Gera o Profile do AutoMapper.
    /// </summary>
    public static string GenerateProfile(EntityInfo info)
    {
        var entityNs = info.Namespace;

        // ✅ Gera ignores para campos protegidos
        var createIgnores = GenerateCreateIgnores(info);
        var updateIgnores = GenerateUpdateIgnores(info);

        // ✅ v4.6: Gera mapeamento de navegações
        var navigationMappings = GenerateNavigationMappings(info);

        return $$"""
{{info.FileHeader}}
using System;
using System.Collections.Generic;
using AutoMapper;
using {{entityNs}};
using {{info.DtoNamespace}};

namespace {{info.MapperNamespace}};

/// <summary>
/// Perfil de mapeamento do AutoMapper para {{info.DisplayName}}.
/// </summary>
public sealed class {{info.EntityName}}Profile : Profile
{
    public {{info.EntityName}}Profile()
    {
        // Entity → DTO
        CreateMap<{{info.EntityName}}, {{info.EntityName}}Dto>(){{navigationMappings}};

        // CreateRequest → Entity
        CreateMap<Create{{info.EntityName}}Request, {{info.EntityName}}>()
{{createIgnores}}
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

        // UpdateRequest → Entity
        CreateMap<Update{{info.EntityName}}Request, {{info.EntityName}}>()
{{updateIgnores}}
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));
    }
}
""";
    }

    // =========================================================================
    // ✅ v4.6.1: MAPEAMENTO DE NAVEGAÇÕES
    // =========================================================================

    private static string GenerateNavigationMappings(EntityInfo info)
    {
        var navProps = info.Navigations
            .Where(n => n.HasNavigationDisplay &&
                       n.RelationshipType == NavigationRelationshipType.ManyToOne)
            .ToList();

        if (!navProps.Any())
            return "";

        var lines = new List<string>();

        foreach (var nav in navProps)
        {
            var dtoProp = nav.DtoPropertyNameComputed;
            var navName = nav.Name;
            var displayProp = nav.DisplayProperty;

            lines.Add($"            .ForMember(dest => dest.{dtoProp}, opt => opt.MapFrom(src => src.{navName} != null ? src.{navName}.{displayProp} : null))");
        }

        return "\n" + string.Join("\n", lines);
    }

    /// <summary>
    /// Gera ignores para CreateRequest.
    /// v4.8: Só ignora PK auto-gerada (Identity/Guid). PK texto/numérica NÃO é ignorada.
    /// v4.7: Ignora TODAS as colunas de PK composta.
    /// </summary>
    private static string GenerateCreateIgnores(EntityInfo info)
    {
        var ignores = new List<string>();

        // =====================================================================
        // v4.8: Lógica de PK no Create
        // - PK composta: NÃO ignora (precisam ser informadas)
        // - PK Identity/Guid: IGNORA (auto-gerada pelo banco)
        // - PK texto/numérica não-identity: NÃO ignora (informada pelo usuário)
        // =====================================================================
        if (info.HasCompositeKey)
        {
            // PK composta: NÃO ignora as PKs no Create (elas precisam ser informadas!)
        }
        else
        {
            var pkProp = info.Properties.FirstOrDefault(p => p.IsPrimaryKey);
            bool isPkAutoGenerated = pkProp != null && (pkProp.IsIdentity || pkProp.IsGuid);

            if (isPkAutoGenerated)
            {
                // PK auto-gerada: ignora no mapeamento Create
                ignores.Add($"            .ForMember(dest => dest.{info.PrimaryKeyProperty}, opt => opt.Ignore())");
            }
            // PK texto/numérica não-identity: NÃO ignora (valor vem do request)
        }

        // Ignora TenantId (se não for legada)
        if (!info.IsLegacyTable)
        {
            var tenantFields = new[] { "TenantId", "IdSaas", "IdTenant" };
            foreach (var field in tenantFields)
            {
                if (info.Properties.Any(p => p.Name == field))
                {
                    ignores.Add($"            .ForMember(dest => dest.{field}, opt => opt.Ignore())");
                }
            }
        }

        // Ignora campos de auditoria
        if (!string.IsNullOrEmpty(info.CreatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.CreatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedByField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedByField}, opt => opt.Ignore())");

        // ✅ v4.6: Ignora propriedades de navegação
        var navIgnores = GenerateNavigationIgnores(info);
        ignores.AddRange(navIgnores);

        return string.Join("\n", ignores);
    }

    /// <summary>
    /// Gera ignores para UpdateRequest.
    /// v4.7: Ignora TODAS as colunas de PK composta.
    /// </summary>
    private static string GenerateUpdateIgnores(EntityInfo info)
    {
        var ignores = new List<string>();

        // ✅ v4.7: Ignora PK(s) - no Update, SEMPRE ignora todas as PKs
        if (info.HasCompositeKey)
        {
            foreach (var pkProp in info.CompositeKeyProperties)
            {
                ignores.Add($"            .ForMember(dest => dest.{pkProp}, opt => opt.Ignore())");
            }
        }
        else
        {
            ignores.Add($"            .ForMember(dest => dest.{info.PrimaryKeyProperty}, opt => opt.Ignore())");
        }

        // Ignora TenantId
        if (!info.IsLegacyTable)
        {
            var tenantFields = new[] { "TenantId", "IdSaas", "IdTenant" };
            foreach (var field in tenantFields)
            {
                if (info.Properties.Any(p => p.Name == field))
                {
                    ignores.Add($"            .ForMember(dest => dest.{field}, opt => opt.Ignore())");
                }
            }
        }

        // Ignora TODOS campos de auditoria
        if (!string.IsNullOrEmpty(info.CreatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.CreatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedByField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedByField}, opt => opt.Ignore())");

        // ✅ v4.6: Ignora propriedades de navegação
        var navIgnores = GenerateNavigationIgnores(info);
        ignores.AddRange(navIgnores);

        return string.Join("\n", ignores);
    }

    private static List<string> GenerateNavigationIgnores(EntityInfo info)
    {
        var ignores = new List<string>();

        var navWithDisplay = info.Navigations
            .Where(n => n.HasNavigationDisplay &&
                       n.RelationshipType == NavigationRelationshipType.ManyToOne)
            .ToList();

        foreach (var nav in navWithDisplay)
        {
            ignores.Add($"            .ForMember(dest => dest.{nav.Name}, opt => opt.Ignore())");
        }

        return ignores;
    }
}