// =============================================================================
// RHSENSOERP GENERATOR v4.9 - MAPPER TEMPLATE
// =============================================================================
// v4.9: FIX CRÍTICO - Ignora Id (Guid/Identity) no Update quando NÃO é PK
//       Sem isso, AutoMapper sobrescreve entity.Id com Guid.Empty porque
//       Guid.Empty NÃO é null (a condição srcMember != null NÃO protege)
// v4.8: CORRIGIDO - PK texto/numérica não-identity NÃO é ignorada no Create
// v4.7: ADICIONADO - Suporte a PK composta (ignora todas as colunas da PK)
// v4.6.1: CORRIGIDO - Null-check explícito em navegações
// v4.6: ADICIONADO - Mapeamento automático de navegações
// =============================================================================
using RhSensoERP.Generators.Models;
using System.Collections.Generic;
using System.Linq;

namespace RhSensoERP.Generators.Templates;

/// <summary>
/// Template para geração de AutoMapper Profile.
/// </summary>
public static class MapperTemplate
{
    /// <summary>
    /// Gera o Profile do AutoMapper.
    /// </summary>
    public static string GenerateProfile(EntityInfo info)
    {
        var entityNs = info.Namespace;

        // ✅ Gera ignores para campos protegidos
        var createIgnores = GenerateCreateIgnores(info);
        var updateIgnores = GenerateUpdateIgnores(info);

        // ✅ v4.6: Gera mapeamento de navegações
        var navigationMappings = GenerateNavigationMappings(info);

        return $$"""
{{info.FileHeader}}
using System;
using System.Collections.Generic;
using AutoMapper;
using {{entityNs}};
using {{info.DtoNamespace}};

namespace {{info.MapperNamespace}};

/// <summary>
/// Perfil de mapeamento do AutoMapper para {{info.DisplayName}}.
/// </summary>
public sealed class {{info.EntityName}}Profile : Profile
{
    public {{info.EntityName}}Profile()
    {
        // Entity → DTO
        CreateMap<{{info.EntityName}}, {{info.EntityName}}Dto>(){{navigationMappings}};

        // CreateRequest → Entity
        CreateMap<Create{{info.EntityName}}Request, {{info.EntityName}}>()
{{createIgnores}}
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

        // UpdateRequest → Entity
        CreateMap<Update{{info.EntityName}}Request, {{info.EntityName}}>()
{{updateIgnores}}
            .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));
    }
}
""";
    }

    // =========================================================================
    // ✅ v4.6.1: MAPEAMENTO DE NAVEGAÇÕES
    // =========================================================================

    private static string GenerateNavigationMappings(EntityInfo info)
    {
        var navProps = info.Navigations
            .Where(n => n.HasNavigationDisplay &&
                       n.RelationshipType == NavigationRelationshipType.ManyToOne)
            .ToList();

        if (!navProps.Any())
            return "";

        var lines = new List<string>();

        foreach (var nav in navProps)
        {
            var dtoProp = nav.DtoPropertyNameComputed;
            var navName = nav.Name;
            var displayProp = nav.DisplayProperty;

            lines.Add($"            .ForMember(dest => dest.{dtoProp}, opt => opt.MapFrom(src => src.{navName} != null ? src.{navName}.{displayProp} : null))");
        }

        return "\n" + string.Join("\n", lines);
    }

    /// <summary>
    /// Gera ignores para CreateRequest.
    /// v4.8: Só ignora PK auto-gerada (Identity/Guid). PK texto/numérica NÃO é ignorada.
    /// v4.7: Ignora TODAS as colunas de PK composta.
    /// </summary>
    private static string GenerateCreateIgnores(EntityInfo info)
    {
        var ignores = new List<string>();

        // =====================================================================
        // v4.8: Lógica de PK no Create
        // - PK composta: NÃO ignora (precisam ser informadas)
        // - PK Identity/Guid: IGNORA (auto-gerada pelo banco)
        // - PK texto/numérica não-identity: NÃO ignora (informada pelo usuário)
        // =====================================================================
        if (info.HasCompositeKey)
        {
            // PK composta: NÃO ignora as PKs no Create (elas precisam ser informadas!)

            // ✅ v4.9: Ignora Id (Guid/Identity) quando NÃO faz parte da PK composta
            // Ex: GrupoDeUsuario tem PK(CdSistema, CdGrUser) + campo Id (Guid) herdado
            // O Id é auto-gerado e NÃO deve ser mapeado do request
            foreach (var prop in info.Properties)
            {
                if (prop.IsPrimaryKey) continue; // PK composta: não ignora
                if (IsAutoGeneratedField(prop))
                {
                    ignores.Add($"            .ForMember(dest => dest.{prop.Name}, opt => opt.Ignore())");
                }
            }
        }
        else
        {
            var pkProp = info.Properties.FirstOrDefault(p => p.IsPrimaryKey);
            bool isPkAutoGenerated = pkProp != null && (pkProp.IsIdentity || pkProp.IsGuid);

            if (isPkAutoGenerated)
            {
                // PK auto-gerada: ignora no mapeamento Create
                ignores.Add($"            .ForMember(dest => dest.{info.PrimaryKeyProperty}, opt => opt.Ignore())");
            }
            // PK texto/numérica não-identity: NÃO ignora (valor vem do request)
        }

        // Ignora TenantId (se não for legada)
        if (!info.IsLegacyTable)
        {
            var tenantFields = new[] { "TenantId", "IdSaas", "IdTenant" };
            foreach (var field in tenantFields)
            {
                if (info.Properties.Any(p => p.Name == field))
                {
                    ignores.Add($"            .ForMember(dest => dest.{field}, opt => opt.Ignore())");
                }
            }
        }

        // Ignora campos de auditoria
        if (!string.IsNullOrEmpty(info.CreatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.CreatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedByField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedByField}, opt => opt.Ignore())");

        // ✅ v4.6: Ignora propriedades de navegação
        var navIgnores = GenerateNavigationIgnores(info);
        ignores.AddRange(navIgnores);

        return string.Join("\n", ignores);
    }

    /// <summary>
    /// Gera ignores para UpdateRequest.
    /// ⭐ v4.9: Ignora Id (Guid/Identity) quando NÃO é PK.
    /// v4.7: Ignora TODAS as colunas de PK composta.
    /// </summary>
    private static string GenerateUpdateIgnores(EntityInfo info)
    {
        var ignores = new List<string>();

        // ✅ v4.7: Ignora PK(s) - no Update, SEMPRE ignora todas as PKs
        if (info.HasCompositeKey)
        {
            foreach (var pkProp in info.CompositeKeyProperties)
            {
                ignores.Add($"            .ForMember(dest => dest.{pkProp}, opt => opt.Ignore())");
            }

            // =================================================================
            // ⭐ v4.9 FIX CRÍTICO: Ignora campos auto-gerados que NÃO são PK
            // 
            // Em entidades com PK composta (ex: CdSistema + CdGrUser), pode
            // existir um campo Id (Guid) herdado de BaseEntity que NÃO faz 
            // parte da PK. Este campo é auto-gerado e NÃO deve ser mapeado.
            //
            // Sem este Ignore, AutoMapper copia Guid.Empty (default do request
            // que não envia Id) para entity.Id, sobrescrevendo o valor real.
            // A condição srcMember != null NÃO protege value types:
            //   Guid.Empty != null → true → AutoMapper copia o valor!
            //
            // O mesmo vale para TenantId em tabelas legadas (IsLegacyTable=true)
            // onde o filtro de TenantId acima não é aplicado.
            // =================================================================
            foreach (var prop in info.Properties)
            {
                if (prop.IsPrimaryKey) continue; // já ignorado acima
                if (IsAutoGeneratedField(prop))
                {
                    // Evita duplicata se já foi ignorado por outra regra
                    var ignoreLine = $"            .ForMember(dest => dest.{prop.Name}, opt => opt.Ignore())";
                    if (!ignores.Contains(ignoreLine))
                    {
                        ignores.Add(ignoreLine);
                    }
                }
            }
        }
        else
        {
            ignores.Add($"            .ForMember(dest => dest.{info.PrimaryKeyProperty}, opt => opt.Ignore())");
        }

        // Ignora TenantId
        if (!info.IsLegacyTable)
        {
            var tenantFields = new[] { "TenantId", "IdSaas", "IdTenant" };
            foreach (var field in tenantFields)
            {
                if (info.Properties.Any(p => p.Name == field))
                {
                    var ignoreLine = $"            .ForMember(dest => dest.{field}, opt => opt.Ignore())";
                    if (!ignores.Contains(ignoreLine))
                    {
                        ignores.Add(ignoreLine);
                    }
                }
            }
        }

        // Ignora TODOS campos de auditoria
        if (!string.IsNullOrEmpty(info.CreatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.CreatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.CreatedByField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedAtField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedAtField}, opt => opt.Ignore())");

        if (!string.IsNullOrEmpty(info.UpdatedByField))
            ignores.Add($"            .ForMember(dest => dest.{info.UpdatedByField}, opt => opt.Ignore())");

        // ✅ v4.6: Ignora propriedades de navegação
        var navIgnores = GenerateNavigationIgnores(info);
        ignores.AddRange(navIgnores);

        return string.Join("\n", ignores);
    }

    // =========================================================================
    // ⭐ v4.9: HELPER - Detecta campo auto-gerado (Guid Identity, etc.)
    // =========================================================================

    /// <summary>
    /// Verifica se uma propriedade é auto-gerada (Identity, Guid com nome "Id").
    /// Esses campos NÃO devem ser mapeados do Request porque:
    /// - O valor default (Guid.Empty, 0) NÃO é null
    /// - A condição srcMember != null NÃO protege value types
    /// - AutoMapper vai sobrescrever o valor real da entidade tracked
    /// </summary>
    private static bool IsAutoGeneratedField(RhSensoERP.Generators.Models.PropertyInfo prop)
    {
        // Campo Identity (auto-incremento)
        if (prop.IsIdentity)
            return true;

        // Campo Guid chamado "Id" (convenção BaseEntity)
        if (prop.IsGuid && prop.Name.Equals("Id", StringComparison.OrdinalIgnoreCase))
            return true;

        // Campo "Id" que é numérico (int/long) - normalmente auto-gerado
        if (prop.Name.Equals("Id", StringComparison.OrdinalIgnoreCase) &&
            (prop.Type == "int" || prop.Type == "long" || prop.Type == "Guid"))
            return true;

        return false;
    }

    private static List<string> GenerateNavigationIgnores(EntityInfo info)
    {
        var ignores = new List<string>();

        var navWithDisplay = info.Navigations
            .Where(n => n.HasNavigationDisplay &&
                       n.RelationshipType == NavigationRelationshipType.ManyToOne)
            .ToList();

        foreach (var nav in navWithDisplay)
        {
            ignores.Add($"            .ForMember(dest => dest.{nav.Name}, opt => opt.Ignore())");
        }

        return ignores;
    }
}