// =============================================================================
// RHSENSOERP GENERATOR v3.2 - METADATA TEMPLATE
// =============================================================================
// Arquivo: src/Generators/Templates/MetadataTemplate.cs
// Versão: 3.2 - CORRIGIDO: IsIdentity e TimeSpan
// =============================================================================
using RhSensoERP.Generators.Models;
using System.Collections.Generic;
using System.Linq;

namespace RhSensoERP.Generators.Templates;

/// <summary>
/// Template para geração de MetadataProvider.
/// Gera metadados completos da entidade para o frontend dinâmico.
/// </summary>
public static class MetadataTemplate
{
    /// <summary>
    /// Gera o MetadataProvider (EntityMetadataProvider.g.cs).
    /// </summary>
    public static string GenerateMetadataProvider(EntityInfo info)
    {
        var propertiesCode = GeneratePropertiesMetadata(info);

        // ✅ CORRIGIDO: Busca a propriedade PK e verifica IsIdentity
        var pkProp = info.Properties.FirstOrDefault(p => p.Name == info.PrimaryKeyProperty);
        var isIdentity = pkProp?.IsIdentity ?? false;

        return $$"""
// =============================================================================
// ARQUIVO GERADO AUTOMATICAMENTE - NÃO EDITAR MANUALMENTE
// Generator: RhSensoERP.Generators v3.2
// Entity: {{info.EntityName}}
// =============================================================================
using System;
using System.Collections.Generic;
using RhSensoERP.Shared.Application.Metadata;

namespace {{info.ModuleNamespace}}.Application.Metadata;

/// <summary>
/// Provider de metadados para {{info.DisplayName}}.
/// Usado pelo frontend dinâmico para renderizar UI.
/// </summary>
public static class {{info.EntityName}}MetadataProvider
{
    /// <summary>
    /// Retorna os metadados completos da entidade.
    /// </summary>
    public static EntityMetadata GetMetadata() => new()
    {
        // =====================================================================
        // IDENTIFICAÇÃO
        // =====================================================================
        EntityName = "{{info.EntityName}}",
        DisplayName = "{{info.DisplayName}} [{{info.GeneratorVersion}}]",
        PluralName = "{{info.PluralName}}",
        ModuleName = "{{info.ModuleName}}",

        // =====================================================================
        // CHAVE PRIMÁRIA
        // =====================================================================
        PrimaryKey = new PrimaryKeyMetadata
        {
            PropertyName = "{{info.PrimaryKeyProperty}}",
            ColumnName = "{{info.PrimaryKeyColumn}}",
            Type = "{{info.PrimaryKeyType}}",
            IsAutoGenerated = {{FormatBool(isIdentity)}}
        },

        // =====================================================================
        // PERMISSÕES
        // =====================================================================
        Permissions = new PermissionsMetadata
        {
            CdSistema = "{{info.CdSistema}}",
            CdFuncao = "{{info.CdFuncao}}",
            RequiresAuth = {{FormatBool(info.ApiRequiresAuth)}}
        },

        // =====================================================================
        // ENDPOINTS
        // =====================================================================
        Endpoints = new EndpointsMetadata
        {
            BaseUrl = "{{info.ApiFullRoute}}",
            List = "{{info.ApiFullRoute}}",
            GetById = "{{info.ApiFullRoute}}/{id}",
            Create = "{{info.ApiFullRoute}}",
            Update = "{{info.ApiFullRoute}}/{id}",
            Delete = "{{info.ApiFullRoute}}/{id}",
            BatchDelete = "{{info.ApiFullRoute}}/batch",
            Export = "{{info.ApiFullRoute}}/export"
        },

        // =====================================================================
        // PROPRIEDADES
        // =====================================================================
        Properties = new List<PropertyMetadata>
        {
{{propertiesCode}}
        },

        // =====================================================================
        // AÇÕES
        // =====================================================================
        Actions = new ActionsMetadata
        {
            CanCreate = true,
            CanEdit = true,
            CanDelete = true,
            CanBatchDelete = {{FormatBool(info.SupportsBatchDelete)}},
            CanExport = true,
            CanImport = false,
            CanPrint = true,
            CanView = true
        },

        // =====================================================================
        // AÇÕES CUSTOMIZADAS
        // =====================================================================
        CustomActions = new List<CustomActionMetadata>(),

        // =====================================================================
        // CONFIGURAÇÃO DE UI
        // =====================================================================
        UIConfig = new UIConfigMetadata
        {
            Icon = null,
            Color = null,
            PageSize = 10,
            PageSizeOptions = new[] { 10, 25, 50, 100 },
            DefaultSortField = "{{info.PrimaryKeyProperty}}",
            DefaultSortDirection = "asc",
            ShowBreadcrumb = true,
            ShowTitle = true
        }
    };
}
""";
    }

    /// <summary>
    /// Gera o código das propriedades.
    /// </summary>
    private static string GeneratePropertiesMetadata(EntityInfo info)
    {
        var lines = new List<string>();
        var order = 0;

        foreach (var prop in info.Properties)
        {
            var inputType = GetInputType(prop);
            var format = GetFormat(prop);
            var filterType = GetFilterType(prop);

            lines.Add($$"""
            new PropertyMetadata
            {
                // Identificação
                Name = "{{prop.Name}}",
                DisplayName = "{{prop.DisplayName}}",
                Type = "{{prop.Type}}",
                ColumnName = "{{prop.ColumnName}}",

                // Validação
                IsRequired = {{FormatBool(prop.IsRequired)}},
                IsNullable = {{FormatBool(prop.IsNullable)}},
                MaxLength = {{FormatNullableInt(prop.MaxLength)}},
                MinLength = {{FormatNullableInt(prop.MinLength)}},

                // Flags
                IsPrimaryKey = {{FormatBool(prop.IsPrimaryKey)}},
                IsReadOnly = {{FormatBool(prop.IsReadOnly)}},
                ExcludeFromDto = {{FormatBool(prop.ExcludeFromDto)}},

                // Configuração de Lista
                List = new ListPropertyConfig
                {
                    Show = {{FormatBool(ShouldShowInList(prop))}},
                    Order = {{order}},
                    Width = null,
                    Sortable = {{FormatBool(!prop.IsNullable || prop.IsString)}},
                    Filterable = {{FormatBool(prop.IsString)}},
                    Format = "{{format}}",
                    CssClass = null,
                    Align = "{{GetAlign(prop)}}"
                },

                // Configuração de Formulário
                Form = new FormPropertyConfig
                {
                    Show = {{FormatBool(!prop.IsReadOnly && !IsAuditField(prop.Name))}},
                    ShowOnCreate = {{FormatBool(!prop.IsPrimaryKey || prop.Type == "string")}},
                    ShowOnEdit = {{FormatBool(!prop.IsPrimaryKey)}},
                    Order = {{order}},
                    Group = null,
                    InputType = "{{inputType}}",
                    Placeholder = "{{GetPlaceholder(prop)}}",
                    HelpText = null,
                    Mask = null,
                    Rows = 3,
                    ColSize = {{GetColSize(prop)}},
                    Icon = null,
                    Disabled = {{FormatBool(prop.IsReadOnly)}},
                    DefaultValue = null,
                    CssClass = null
                },

                // Configuração de Filtro
                Filter = new FilterPropertyConfig
                {
                    Show = {{FormatBool(prop.IsString && !prop.IsPrimaryKey)}},
                    FilterType = "{{filterType}}",
                    DefaultOperator = "{{GetDefaultOperator(prop)}}",
                    Order = {{order}},
                    Placeholder = "Filtrar por {{prop.DisplayName.ToLower()}}..."
                },

                // Lookup
                Lookup = null
            }
""");
            order++;
        }

        return string.Join(",\n", lines);
    }

    /// <summary>
    /// ✅ CORRIGIDO: Determina o tipo de input HTML baseado no tipo da propriedade.
    /// </summary>
    private static string GetInputType(PropertyInfo prop)
    {
        if (prop.IsBool) return "checkbox";

        // ✅ CORRIGIDO: Detecta TimeSpan especificamente
        if (prop.Type.Contains("TimeSpan")) return "time";

        if (prop.IsDateTime) return prop.Type.Contains("Time") ? "datetime-local" : "date";
        if (prop.IsNumeric) return "number";
        if (prop.IsGuid) return "text";
        if (prop.MaxLength > 255) return "textarea";

        // Inferir por nome
        var nameLower = prop.Name.ToLower();
        if (nameLower.Contains("email")) return "email";
        if (nameLower.Contains("telefone") || nameLower.Contains("phone") || nameLower.Contains("celular")) return "tel";
        if (nameLower.Contains("url") || nameLower.Contains("site") || nameLower.Contains("link")) return "url";
        if (nameLower.Contains("senha") || nameLower.Contains("password")) return "password";

        return "text";
    }

    /// <summary>
    /// Determina o formato de exibição na lista.
    /// </summary>
    private static string GetFormat(PropertyInfo prop)
    {
        if (prop.IsBool) return "boolean";

        // ✅ CORRIGIDO: TimeSpan formatado como time
        if (prop.Type.Contains("TimeSpan")) return "time";

        if (prop.IsDateTime) return prop.Type.Contains("Time") ? "datetime" : "date";

        var nameLower = prop.Name.ToLower();
        if (nameLower.Contains("valor") || nameLower.Contains("preco") || nameLower.Contains("salario")) return "currency";
        if (nameLower.Contains("percent") || nameLower.Contains("taxa")) return "percent";

        return "text";
    }

    /// <summary>
    /// Determina o tipo de filtro.
    /// </summary>
    private static string GetFilterType(PropertyInfo prop)
    {
        if (prop.IsBool) return "boolean";
        if (prop.IsDateTime) return "date";
        if (prop.IsNumeric) return "number";
        return "text";
    }

    /// <summary>
    /// Determina o operador padrão do filtro.
    /// </summary>
    private static string GetDefaultOperator(PropertyInfo prop)
    {
        if (prop.IsString) return "contains";
        if (prop.IsNumeric || prop.IsDateTime) return "equals";
        if (prop.IsBool) return "equals";
        return "equals";
    }

    /// <summary>
    /// Determina o alinhamento da coluna.
    /// </summary>
    private static string GetAlign(PropertyInfo prop)
    {
        if (prop.IsNumeric) return "right";
        if (prop.IsBool) return "center";
        if (prop.IsDateTime) return "center";
        return "left";
    }

    /// <summary>
    /// Gera placeholder baseado na propriedade.
    /// </summary>
    private static string GetPlaceholder(PropertyInfo prop)
    {
        // ✅ CORRIGIDO: Placeholder específico para TimeSpan
        if (prop.Type.Contains("TimeSpan"))
            return "00:00";

        return $"Digite {prop.DisplayName.ToLower()}...";
    }

    /// <summary>
    /// Determina o tamanho da coluna Bootstrap.
    /// </summary>
    private static int GetColSize(PropertyInfo prop)
    {
        if (prop.MaxLength > 255) return 12; // textarea
        if (prop.MaxLength > 100) return 8;
        if (prop.IsBool) return 3;
        if (prop.IsDateTime) return 4;
        if (prop.Type.Contains("TimeSpan")) return 3; // ✅ TimeSpan é pequeno
        return 6;
    }

    /// <summary>
    /// Verifica se é campo de auditoria.
    /// </summary>
    private static bool IsAuditField(string name)
    {
        return name is "CreatedAt" or "CreatedBy" or "UpdatedAt" or "UpdatedBy"
            or "Aud_CreatedAt" or "Aud_IdUsuarioCadastro" or "Aud_UpdatedAt" or "Aud_IdUsuarioAtualizacao";
    }

    /// <summary>
    /// Determina se a propriedade deve aparecer na listagem.
    /// PKs do tipo Guid não aparecem, mas PKs string/int aparecem (tabelas legadas).
    /// </summary>
    private static bool ShouldShowInList(PropertyInfo prop)
    {
        // Campos de auditoria nunca aparecem
        if (IsAuditField(prop.Name)) return false;

        // Campos excluídos do DTO nunca aparecem
        if (prop.ExcludeFromDto) return false;

        // PK do tipo Guid não aparece (é só ID interno)
        if (prop.IsPrimaryKey && prop.IsGuid) return false;

        // PK de outros tipos (string, int) aparece (códigos legados)
        // Demais campos aparecem
        return true;
    }

    /// <summary>
    /// Formata booleano para código C#.
    /// </summary>
    private static string FormatBool(bool value) => value ? "true" : "false";

    /// <summary>
    /// Formata int nullable para código C#.
    /// </summary>
    private static string FormatNullableInt(int? value) => value.HasValue ? value.ToString()! : "null";
}