// =============================================================================
// RHSENSOERP GENERATOR v4.6 - METADATA TEMPLATE
// =============================================================================
// v4.6: ADICIONADO - Metadados de navegação (FK escondida, navegação visível)
// v3.2: CORRIGIDO - IsIdentity e TimeSpan
// =============================================================================
using RhSensoERP.Generators.Models;
using System.Collections.Generic;
using System.Linq;

namespace RhSensoERP.Generators.Templates;

/// <summary>
/// Template para geração de MetadataProvider.
/// Gera metadados completos da entidade para o frontend dinâmico.
/// </summary>
public static class MetadataTemplate
{
    /// <summary>
    /// Gera o MetadataProvider (EntityMetadataProvider.g.cs).
    /// </summary>
    public static string GenerateMetadataProvider(EntityInfo info)
    {
        var propertiesCode = GeneratePropertiesMetadata(info);

        var pkProp = info.Properties.FirstOrDefault(p => p.Name == info.PrimaryKeyProperty);
        var isIdentity = pkProp?.IsIdentity ?? false;

        return $$"""
{{info.FileHeader}}
using System;
using System.Collections.Generic;
using RhSensoERP.Shared.Application.Metadata;

namespace {{info.ModuleNamespace}}.Application.Metadata;

/// <summary>
/// Provider de metadados para {{info.DisplayName}}.
/// Usado pelo frontend dinâmico para renderizar UI.
/// </summary>
public static class {{info.EntityName}}MetadataProvider
{
    /// <summary>
    /// Retorna os metadados completos da entidade.
    /// </summary>
    public static EntityMetadata GetMetadata() => new()
    {
        // =====================================================================
        // IDENTIFICAÇÃO
        // =====================================================================
        EntityName = "{{info.EntityName}}",
        DisplayName = "{{info.DisplayName}} [{{info.GeneratorVersion}}]",
        PluralName = "{{info.PluralName}}",
        ModuleName = "{{info.ModuleName}}",

        // =====================================================================
        // CHAVE PRIMÁRIA
        // =====================================================================
        PrimaryKey = new PrimaryKeyMetadata
        {
            PropertyName = "{{info.PrimaryKeyProperty}}",
            ColumnName = "{{info.PrimaryKeyColumn}}",
            Type = "{{info.PrimaryKeyType}}",
            IsAutoGenerated = {{FormatBool(isIdentity)}}
        },

        // =====================================================================
        // PERMISSÕES
        // =====================================================================
        Permissions = new PermissionsMetadata
        {
            CdSistema = "{{info.CdSistema}}",
            CdFuncao = "{{info.CdFuncao}}",
            RequiresAuth = {{FormatBool(info.ApiRequiresAuth)}}
        },

        // =====================================================================
        // ENDPOINTS
        // =====================================================================
        Endpoints = new EndpointsMetadata
        {
            BaseUrl = "{{info.ApiFullRoute}}",
            List = "{{info.ApiFullRoute}}",
            GetById = "{{info.ApiFullRoute}}/{id}",
            Create = "{{info.ApiFullRoute}}",
            Update = "{{info.ApiFullRoute}}/{id}",
            Delete = "{{info.ApiFullRoute}}/{id}",
            BatchDelete = "{{info.ApiFullRoute}}/batch",
            Export = "{{info.ApiFullRoute}}/export"
        },

        // =====================================================================
        // PROPRIEDADES
        // =====================================================================
        Properties = new List<PropertyMetadata>
        {
{{propertiesCode}}
        },

        // =====================================================================
        // AÇÕES
        // =====================================================================
        Actions = new ActionsMetadata
        {
            CanCreate = true,
            CanEdit = true,
            CanDelete = true,
            CanBatchDelete = {{FormatBool(info.SupportsBatchDelete)}},
            CanExport = true,
            CanImport = false,
            CanPrint = true,
            CanView = true
        },

        // =====================================================================
        // AÇÕES CUSTOMIZADAS
        // =====================================================================
        CustomActions = new List<CustomActionMetadata>(),

        // =====================================================================
        // CONFIGURAÇÃO DE UI
        // =====================================================================
        UIConfig = new UIConfigMetadata
        {
            Icon = null,
            Color = null,
            PageSize = 10,
            PageSizeOptions = new[] { 10, 25, 50, 100 },
            DefaultSortField = "{{info.PrimaryKeyProperty}}",
            DefaultSortDirection = "asc",
            ShowBreadcrumb = true,
            ShowTitle = true
        }
    };
}
""";
    }

    /// <summary>
    /// Gera o código das propriedades.
    /// v4.6: Adiciona propriedades de navegação e esconde FKs com navegação.
    /// </summary>
    private static string GeneratePropertiesMetadata(EntityInfo info)
    {
        var lines = new List<string>();
        var order = 0;

        // ✅ FKs com navegação (para lookup no form)
        var fksWithNavigation = GetForeignKeysWithNavigation(info);

        foreach (var prop in info.Properties)
        {
            var isFkWithNav = fksWithNavigation.Contains(prop.Name);

            // Se é FK com navegação, configura como Select2
            var inputType = isFkWithNav
                ? "select"
                : GetInputType(prop);

            var format = GetFormat(prop);
            var filterType = GetFilterType(prop);

            // ✅ FK com navegação: NÃO aparece no grid, SÓ no form
            var showInList = isFkWithNav ? false : ShouldShowInList(prop);

            // ✅ FK com navegação: Gera config de Lookup
            var lookupConfig = isFkWithNav
                ? GenerateLookupConfig(prop.Name, info)
                : "null";

            lines.Add($$"""
            new PropertyMetadata
            {
                // Identificação
                Name = "{{prop.Name}}",
                DisplayName = "{{prop.DisplayName}}",
                Type = "{{prop.Type}}",
                ColumnName = "{{prop.ColumnName}}",

                // Validação
                IsRequired = {{FormatBool(prop.IsRequired)}},
                IsNullable = {{FormatBool(prop.IsNullable)}},
                MaxLength = {{FormatNullableInt(prop.MaxLength)}},
                MinLength = {{FormatNullableInt(prop.MinLength)}},

                // Flags
                IsPrimaryKey = {{FormatBool(prop.IsPrimaryKey)}},
                IsReadOnly = {{FormatBool(prop.IsReadOnly)}},
                ExcludeFromDto = {{FormatBool(prop.ExcludeFromDto)}},

                // Configuração de Lista
                List = new ListPropertyConfig
                {
                    Show = {{FormatBool(showInList)}},
                    Order = {{order}},
                    Width = null,
                    Sortable = {{FormatBool(!prop.IsNullable || prop.IsString)}},
                    Filterable = {{FormatBool(prop.IsString)}},
                    Format = "{{format}}",
                    CssClass = null,
                    Align = "{{GetAlign(prop)}}"
                },

                // Configuração de Formulário
                Form = new FormPropertyConfig
                {
                    Show = {{FormatBool(!prop.IsReadOnly && !IsAuditField(prop.Name))}},
                    ShowOnCreate = {{FormatBool(!prop.IsPrimaryKey || prop.Type == "string")}},
                    ShowOnEdit = {{FormatBool(!prop.IsPrimaryKey)}},
                    Order = {{order}},
                    Group = null,
                    InputType = "{{inputType}}",
                    Placeholder = "{{GetPlaceholder(prop)}}",
                    HelpText = null,
                    Mask = null,
                    Rows = 3,
                    ColSize = {{GetColSize(prop)}},
                    Icon = null,
                    Disabled = {{FormatBool(prop.IsReadOnly)}},
                    DefaultValue = null,
                    CssClass = null
                },

                // Configuração de Filtro
                Filter = new FilterPropertyConfig
                {
                    Show = {{FormatBool(prop.IsString && !prop.IsPrimaryKey)}},
                    FilterType = "{{filterType}}",
                    DefaultOperator = "{{GetDefaultOperator(prop)}}",
                    Order = {{order}},
                    Placeholder = "Filtrar por {{prop.DisplayName.ToLower()}}..."
                },

                // Lookup
                Lookup = {{lookupConfig}}
            }
""");
            order++;
        }

        // ✅ v4.6 NOVO: Adiciona propriedades de navegação
        var navProperties = GenerateNavigationPropertiesMetadata(info, ref order);
        if (!string.IsNullOrEmpty(navProperties))
        {
            lines.Add(navProperties);
        }

        return string.Join(",\n", lines);
    }

    // =========================================================================
    // ✅ v4.6 NOVO: METADADOS DE NAVEGAÇÃO
    // =========================================================================

    /// <summary>
    /// Gera metadados para propriedades de navegação.
    /// Estas propriedades aparecem NO GRID mas NÃO NO FORM.
    /// </summary>
    private static string GenerateNavigationPropertiesMetadata(EntityInfo info, ref int order)
    {
        var navWithDisplay = info.Navigations
            .Where(n => n.HasNavigationDisplay &&
                       n.GridColumn &&
                       n.RelationshipType == NavigationRelationshipType.ManyToOne)
            .OrderBy(n => n.GridOrder)
            .ToList();

        if (!navWithDisplay.Any())
            return "";

        var lines = new List<string>();
        var isFirst = true;  // ✅ CONTROLA SE É A PRIMEIRA

        foreach (var nav in navWithDisplay)
        {
            var dtoPropName = nav.DtoPropertyNameComputed;
            var displayName = nav.GridHeaderComputed;

            // ✅ PRIMEIRA navegação: SEM vírgula
            // ✅ DEMAIS navegações: COM vírgula
            var comma = isFirst ? "" : ",";
            isFirst = false;

            lines.Add($@"{comma}
            new PropertyMetadata
            {{
                // Identificação
                Name = ""{dtoPropName}"",
                DisplayName = ""{displayName}"",
                Type = ""string"",
                ColumnName = ""{dtoPropName}"",

                // Validação
                IsRequired = false,
                IsNullable = true,
                MaxLength = null,
                MinLength = null,

                // Flags
                IsPrimaryKey = false,
                IsReadOnly = true,
                ExcludeFromDto = false,

                // Configuração de Lista
                List = new ListPropertyConfig
                {{
                    Show = true,
                    Order = {order},
                    Width = null,
                    Sortable = false,
                    Filterable = false,
                    Format = ""text"",
                    CssClass = null,
                    Align = ""left""
                }},

                // Configuração de Formulário
                Form = new FormPropertyConfig
                {{
                    Show = false,
                    ShowOnCreate = false,
                    ShowOnEdit = false,
                    Order = {order},
                    Group = null,
                    InputType = ""text"",
                    Placeholder = """",
                    HelpText = null,
                    Mask = null,
                    Rows = 3,
                    ColSize = 6,
                    Icon = null,
                    Disabled = true,
                    DefaultValue = null,
                    CssClass = null
                }},

                // Configuração de Filtro
                Filter = new FilterPropertyConfig
                {{
                    Show = false,
                    FilterType = ""text"",
                    DefaultOperator = ""contains"",
                    Order = {order},
                    Placeholder = """"
                }},

                // Lookup
                Lookup = null
            }}");

            order++;
        }

        return string.Join("", lines);  // ✅ Junta SEM separador (vírgulas já estão nas strings)
    }

    /// <summary>
    /// Gera configuração de Lookup para FK.
    /// </summary>
    private static string GenerateLookupConfig(string fkPropertyName, EntityInfo info)
    {
        var nav = info.Navigations.FirstOrDefault(n => n.ForeignKeyProperty == fkPropertyName);

        if (nav == null || !nav.HasNavigationDisplay)
            return "null";

        var module = nav.DisplayModule ?? info.ModuleName;
        var moduleRoute = module.ToLowerInvariant();
        var entityRoute = nav.EntityRouteComputed;
        var displayProp = nav.DisplayProperty;

        // Converte para camelCase (RazaoSocial → razaoSocial)
        var displayPropCamel = char.ToLowerInvariant(displayProp[0]) + displayProp.Substring(1);

        return $@"new LookupConfig
                {{
                    Module = ""{module}"",
                    Route = ""{entityRoute}"",
                    Endpoint = ""/api/{moduleRoute}/{entityRoute}/lookup"",
                    ValueField = ""id"",
                    TextField = ""{displayPropCamel}""
                }}";
    }

    /// <summary>
    /// Retorna lista de FKs que têm navegação configurada.
    /// </summary>
    private static List<string> GetForeignKeysWithNavigation(EntityInfo info)
    {
        return info.Navigations
            .Where(n => n.HasNavigationDisplay &&
                       n.RelationshipType == NavigationRelationshipType.ManyToOne &&
                       !string.IsNullOrEmpty(n.ForeignKeyProperty))
            .Select(n => n.ForeignKeyProperty)
            .ToList();
    }

    // =========================================================================
    // MÉTODOS AUXILIARES (MANTIDOS)
    // =========================================================================

    private static string GetInputType(PropertyInfo prop)
    {
        if (prop.IsBool) return "checkbox";
        if (prop.Type.Contains("TimeSpan") || prop.Type.Contains("TimeOnly")) return "time";
        if (prop.IsDateTime) return prop.Type.Contains("Time") ? "datetime-local" : "date";
        if (prop.IsNumeric) return "number";
        if (prop.IsGuid) return "text";
        if (prop.MaxLength > 255) return "textarea";

        var nameLower = prop.Name.ToLower();
        if (nameLower.Contains("email")) return "email";
        if (nameLower.Contains("telefone") || nameLower.Contains("phone") || nameLower.Contains("celular")) return "tel";
        if (nameLower.Contains("url") || nameLower.Contains("site") || nameLower.Contains("link")) return "url";
        if (nameLower.Contains("senha") || nameLower.Contains("password")) return "password";

        return "text";
    }

    private static string GetFormat(PropertyInfo prop)
    {
        if (prop.IsBool) return "boolean";
        if (prop.Type.Contains("TimeSpan") || prop.Type.Contains("TimeOnly")) return "time";
        if (prop.IsDateTime) return prop.Type.Contains("Time") ? "datetime" : "date";

        var nameLower = prop.Name.ToLower();
        if (nameLower.Contains("valor") || nameLower.Contains("preco") || nameLower.Contains("salario")) return "currency";
        if (nameLower.Contains("percent") || nameLower.Contains("taxa")) return "percent";

        return "text";
    }

    private static string GetFilterType(PropertyInfo prop)
    {
        if (prop.IsBool) return "boolean";
        if (prop.IsDateTime) return "date";
        if (prop.IsNumeric) return "number";
        return "text";
    }

    private static string GetDefaultOperator(PropertyInfo prop)
    {
        if (prop.IsString) return "contains";
        if (prop.IsNumeric || prop.IsDateTime) return "equals";
        if (prop.IsBool) return "equals";
        return "equals";
    }

    private static string GetAlign(PropertyInfo prop)
    {
        if (prop.IsNumeric) return "right";
        if (prop.IsBool) return "center";
        if (prop.IsDateTime) return "center";
        return "left";
    }

    private static string GetPlaceholder(PropertyInfo prop)
    {
        if (prop.Type.Contains("TimeSpan") || prop.Type.Contains("TimeOnly"))
            return "00:00";

        return $"Digite {prop.DisplayName.ToLower()}...";
    }

    private static int GetColSize(PropertyInfo prop)
    {
        if (prop.MaxLength > 255) return 12;
        if (prop.MaxLength > 100) return 8;
        if (prop.IsBool) return 3;
        if (prop.IsDateTime) return 4;
        if (prop.Type.Contains("TimeSpan")) return 3;
        return 6;
    }

    private static bool IsAuditField(string name)
    {
        return name is "CreatedAt" or "CreatedBy" or "UpdatedAt" or "UpdatedBy"
            or "Aud_CreatedAt" or "Aud_IdUsuarioCadastro" or "Aud_UpdatedAt" or "Aud_IdUsuarioAtualizacao"
            or "CreatedAtUtc" or "UpdatedAtUtc" or "CreatedByUserId" or "UpdatedByUserId";
    }

    private static bool ShouldShowInList(PropertyInfo prop)
    {
        if (IsAuditField(prop.Name)) return false;
        if (prop.ExcludeFromDto) return false;
        if (prop.IsPrimaryKey && prop.IsGuid) return false;
        return true;
    }

    private static string FormatBool(bool value) => value ? "true" : "false";

    private static string FormatNullableInt(int? value) => value.HasValue ? value.ToString()! : "null";
}